// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: shared/proto/geo/geo.proto

package geopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Location represents a geographical coordinate
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"` // accuracy in meters
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *Location) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Distance calculation request
type DistanceRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Origin            *Location              `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination       *Location              `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	CalculationMethod string                 `protobuf:"bytes,3,opt,name=calculation_method,json=calculationMethod,proto3" json:"calculation_method,omitempty"` // "haversine", "manhattan", "euclidean"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DistanceRequest) Reset() {
	*x = DistanceRequest{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceRequest) ProtoMessage() {}

func (x *DistanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceRequest.ProtoReflect.Descriptor instead.
func (*DistanceRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{1}
}

func (x *DistanceRequest) GetOrigin() *Location {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *DistanceRequest) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *DistanceRequest) GetCalculationMethod() string {
	if x != nil {
		return x.CalculationMethod
	}
	return ""
}

// Distance calculation response
type DistanceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DistanceMeters    float64                `protobuf:"fixed64,1,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	DistanceKm        float64                `protobuf:"fixed64,2,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	BearingDegrees    float64                `protobuf:"fixed64,3,opt,name=bearing_degrees,json=bearingDegrees,proto3" json:"bearing_degrees,omitempty"`
	CalculationMethod string                 `protobuf:"bytes,4,opt,name=calculation_method,json=calculationMethod,proto3" json:"calculation_method,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DistanceResponse) Reset() {
	*x = DistanceResponse{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistanceResponse) ProtoMessage() {}

func (x *DistanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistanceResponse.ProtoReflect.Descriptor instead.
func (*DistanceResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{2}
}

func (x *DistanceResponse) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *DistanceResponse) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *DistanceResponse) GetBearingDegrees() float64 {
	if x != nil {
		return x.BearingDegrees
	}
	return 0
}

func (x *DistanceResponse) GetCalculationMethod() string {
	if x != nil {
		return x.CalculationMethod
	}
	return ""
}

// ETA calculation request
type ETARequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Origin         *Location              `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination    *Location              `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	VehicleType    string                 `protobuf:"bytes,3,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"` // "car", "bike", "walking"
	DepartureTime  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	IncludeTraffic bool                   `protobuf:"varint,5,opt,name=include_traffic,json=includeTraffic,proto3" json:"include_traffic,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ETARequest) Reset() {
	*x = ETARequest{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ETARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETARequest) ProtoMessage() {}

func (x *ETARequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETARequest.ProtoReflect.Descriptor instead.
func (*ETARequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{3}
}

func (x *ETARequest) GetOrigin() *Location {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *ETARequest) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *ETARequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *ETARequest) GetDepartureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureTime
	}
	return nil
}

func (x *ETARequest) GetIncludeTraffic() bool {
	if x != nil {
		return x.IncludeTraffic
	}
	return false
}

// ETA calculation response
type ETAResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DurationSeconds  int32                  `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	DistanceMeters   float64                `protobuf:"fixed64,2,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	RouteSummary     string                 `protobuf:"bytes,3,opt,name=route_summary,json=routeSummary,proto3" json:"route_summary,omitempty"`
	Waypoints        []*Location            `protobuf:"bytes,4,rep,name=waypoints,proto3" json:"waypoints,omitempty"`
	EstimatedArrival *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=estimated_arrival,json=estimatedArrival,proto3" json:"estimated_arrival,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ETAResponse) Reset() {
	*x = ETAResponse{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ETAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETAResponse) ProtoMessage() {}

func (x *ETAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETAResponse.ProtoReflect.Descriptor instead.
func (*ETAResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{4}
}

func (x *ETAResponse) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *ETAResponse) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *ETAResponse) GetRouteSummary() string {
	if x != nil {
		return x.RouteSummary
	}
	return ""
}

func (x *ETAResponse) GetWaypoints() []*Location {
	if x != nil {
		return x.Waypoints
	}
	return nil
}

func (x *ETAResponse) GetEstimatedArrival() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedArrival
	}
	return nil
}

// Nearby drivers request
type NearbyDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Center        *Location              `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,2,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	VehicleTypes  []string               `protobuf:"bytes,4,rep,name=vehicle_types,json=vehicleTypes,proto3" json:"vehicle_types,omitempty"`
	OnlyAvailable bool                   `protobuf:"varint,5,opt,name=only_available,json=onlyAvailable,proto3" json:"only_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyDriversRequest) Reset() {
	*x = NearbyDriversRequest{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyDriversRequest) ProtoMessage() {}

func (x *NearbyDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyDriversRequest.ProtoReflect.Descriptor instead.
func (*NearbyDriversRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{5}
}

func (x *NearbyDriversRequest) GetCenter() *Location {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *NearbyDriversRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *NearbyDriversRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *NearbyDriversRequest) GetVehicleTypes() []string {
	if x != nil {
		return x.VehicleTypes
	}
	return nil
}

func (x *NearbyDriversRequest) GetOnlyAvailable() bool {
	if x != nil {
		return x.OnlyAvailable
	}
	return false
}

// Driver location information
type DriverLocation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DriverId           string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	VehicleId          string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Location           *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	DistanceFromCenter float64                `protobuf:"fixed64,4,opt,name=distance_from_center,json=distanceFromCenter,proto3" json:"distance_from_center,omitempty"`
	Status             string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "online", "busy", "offline"
	VehicleType        string                 `protobuf:"bytes,6,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Rating             float64                `protobuf:"fixed64,7,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DriverLocation) Reset() {
	*x = DriverLocation{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLocation) ProtoMessage() {}

func (x *DriverLocation) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLocation.ProtoReflect.Descriptor instead.
func (*DriverLocation) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{6}
}

func (x *DriverLocation) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverLocation) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *DriverLocation) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *DriverLocation) GetDistanceFromCenter() float64 {
	if x != nil {
		return x.DistanceFromCenter
	}
	return 0
}

func (x *DriverLocation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DriverLocation) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *DriverLocation) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

// Nearby drivers response
type NearbyDriversResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Drivers        []*DriverLocation      `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	TotalCount     int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	SearchRadiusKm float64                `protobuf:"fixed64,3,opt,name=search_radius_km,json=searchRadiusKm,proto3" json:"search_radius_km,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NearbyDriversResponse) Reset() {
	*x = NearbyDriversResponse{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyDriversResponse) ProtoMessage() {}

func (x *NearbyDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyDriversResponse.ProtoReflect.Descriptor instead.
func (*NearbyDriversResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{7}
}

func (x *NearbyDriversResponse) GetDrivers() []*DriverLocation {
	if x != nil {
		return x.Drivers
	}
	return nil
}

func (x *NearbyDriversResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *NearbyDriversResponse) GetSearchRadiusKm() float64 {
	if x != nil {
		return x.SearchRadiusKm
	}
	return 0
}

// Update driver location request
type UpdateDriverLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Location      *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	VehicleId     string                 `protobuf:"bytes,4,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationRequest) Reset() {
	*x = UpdateDriverLocationRequest{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationRequest) ProtoMessage() {}

func (x *UpdateDriverLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDriverLocationRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateDriverLocationRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *UpdateDriverLocationRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateDriverLocationRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

// Update driver location response
type UpdateDriverLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationResponse) Reset() {
	*x = UpdateDriverLocationResponse{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationResponse) ProtoMessage() {}

func (x *UpdateDriverLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDriverLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDriverLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateDriverLocationResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Geohash request
type GeohashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Precision     int32                  `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"` // 1-12, higher = more precise
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeohashRequest) Reset() {
	*x = GeohashRequest{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeohashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeohashRequest) ProtoMessage() {}

func (x *GeohashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeohashRequest.ProtoReflect.Descriptor instead.
func (*GeohashRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{10}
}

func (x *GeohashRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *GeohashRequest) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

// Geohash response
type GeohashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geohash       string                 `protobuf:"bytes,1,opt,name=geohash,proto3" json:"geohash,omitempty"`
	Center        *Location              `protobuf:"bytes,2,opt,name=center,proto3" json:"center,omitempty"`
	WidthMeters   float64                `protobuf:"fixed64,3,opt,name=width_meters,json=widthMeters,proto3" json:"width_meters,omitempty"`
	HeightMeters  float64                `protobuf:"fixed64,4,opt,name=height_meters,json=heightMeters,proto3" json:"height_meters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeohashResponse) Reset() {
	*x = GeohashResponse{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeohashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeohashResponse) ProtoMessage() {}

func (x *GeohashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeohashResponse.ProtoReflect.Descriptor instead.
func (*GeohashResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{11}
}

func (x *GeohashResponse) GetGeohash() string {
	if x != nil {
		return x.Geohash
	}
	return ""
}

func (x *GeohashResponse) GetCenter() *Location {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *GeohashResponse) GetWidthMeters() float64 {
	if x != nil {
		return x.WidthMeters
	}
	return 0
}

func (x *GeohashResponse) GetHeightMeters() float64 {
	if x != nil {
		return x.HeightMeters
	}
	return 0
}

// Route optimization request
type RouteOptimizationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Start            *Location              `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Waypoints        []*Location            `protobuf:"bytes,2,rep,name=waypoints,proto3" json:"waypoints,omitempty"`
	End              *Location              `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	OptimizationType string                 `protobuf:"bytes,4,opt,name=optimization_type,json=optimizationType,proto3" json:"optimization_type,omitempty"` // "shortest", "fastest", "fuel_efficient"
	VehicleType      string                 `protobuf:"bytes,5,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RouteOptimizationRequest) Reset() {
	*x = RouteOptimizationRequest{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteOptimizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteOptimizationRequest) ProtoMessage() {}

func (x *RouteOptimizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteOptimizationRequest.ProtoReflect.Descriptor instead.
func (*RouteOptimizationRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{12}
}

func (x *RouteOptimizationRequest) GetStart() *Location {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RouteOptimizationRequest) GetWaypoints() []*Location {
	if x != nil {
		return x.Waypoints
	}
	return nil
}

func (x *RouteOptimizationRequest) GetEnd() *Location {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *RouteOptimizationRequest) GetOptimizationType() string {
	if x != nil {
		return x.OptimizationType
	}
	return ""
}

func (x *RouteOptimizationRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

// Route optimization response
type RouteOptimizationResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	OptimizedRoute           []*Location            `protobuf:"bytes,1,rep,name=optimized_route,json=optimizedRoute,proto3" json:"optimized_route,omitempty"`
	TotalDistanceKm          float64                `protobuf:"fixed64,2,opt,name=total_distance_km,json=totalDistanceKm,proto3" json:"total_distance_km,omitempty"`
	EstimatedDurationSeconds int32                  `protobuf:"varint,3,opt,name=estimated_duration_seconds,json=estimatedDurationSeconds,proto3" json:"estimated_duration_seconds,omitempty"`
	OptimizationAlgorithm    string                 `protobuf:"bytes,4,opt,name=optimization_algorithm,json=optimizationAlgorithm,proto3" json:"optimization_algorithm,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RouteOptimizationResponse) Reset() {
	*x = RouteOptimizationResponse{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteOptimizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteOptimizationResponse) ProtoMessage() {}

func (x *RouteOptimizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteOptimizationResponse.ProtoReflect.Descriptor instead.
func (*RouteOptimizationResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{13}
}

func (x *RouteOptimizationResponse) GetOptimizedRoute() []*Location {
	if x != nil {
		return x.OptimizedRoute
	}
	return nil
}

func (x *RouteOptimizationResponse) GetTotalDistanceKm() float64 {
	if x != nil {
		return x.TotalDistanceKm
	}
	return 0
}

func (x *RouteOptimizationResponse) GetEstimatedDurationSeconds() int32 {
	if x != nil {
		return x.EstimatedDurationSeconds
	}
	return 0
}

func (x *RouteOptimizationResponse) GetOptimizationAlgorithm() string {
	if x != nil {
		return x.OptimizationAlgorithm
	}
	return ""
}

// Driver location update subscription request
type SubscribeToDriverLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaId        string                 `protobuf:"bytes,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`          // Geographic area to monitor (geohash or area identifier)
	RadiusKm      float64                `protobuf:"fixed64,2,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`  // Radius around the area
	DriverIds     []string               `protobuf:"bytes,3,rep,name=driver_ids,json=driverIds,proto3" json:"driver_ids,omitempty"` // Specific drivers to track (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToDriverLocationRequest) Reset() {
	*x = SubscribeToDriverLocationRequest{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToDriverLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToDriverLocationRequest) ProtoMessage() {}

func (x *SubscribeToDriverLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToDriverLocationRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToDriverLocationRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribeToDriverLocationRequest) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

func (x *SubscribeToDriverLocationRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *SubscribeToDriverLocationRequest) GetDriverIds() []string {
	if x != nil {
		return x.DriverIds
	}
	return nil
}

// Real-time driver location event
type DriverLocationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Location      *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "available", "busy", "offline"
	VehicleId     string                 `protobuf:"bytes,4,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	SpeedKmh      float64                `protobuf:"fixed64,5,opt,name=speed_kmh,json=speedKmh,proto3" json:"speed_kmh,omitempty"`
	Heading       float64                `protobuf:"fixed64,6,opt,name=heading,proto3" json:"heading,omitempty"` // Direction in degrees
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLocationEvent) Reset() {
	*x = DriverLocationEvent{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLocationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLocationEvent) ProtoMessage() {}

func (x *DriverLocationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLocationEvent.ProtoReflect.Descriptor instead.
func (*DriverLocationEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{15}
}

func (x *DriverLocationEvent) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverLocationEvent) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *DriverLocationEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DriverLocationEvent) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *DriverLocationEvent) GetSpeedKmh() float64 {
	if x != nil {
		return x.SpeedKmh
	}
	return 0
}

func (x *DriverLocationEvent) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *DriverLocationEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DriverLocationEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Location tracking session request
type StartLocationTrackingRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DriverId              string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	UpdateIntervalSeconds int32                  `protobuf:"varint,2,opt,name=update_interval_seconds,json=updateIntervalSeconds,proto3" json:"update_interval_seconds,omitempty"` // How often to send updates
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StartLocationTrackingRequest) Reset() {
	*x = StartLocationTrackingRequest{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLocationTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLocationTrackingRequest) ProtoMessage() {}

func (x *StartLocationTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLocationTrackingRequest.ProtoReflect.Descriptor instead.
func (*StartLocationTrackingRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{16}
}

func (x *StartLocationTrackingRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *StartLocationTrackingRequest) GetUpdateIntervalSeconds() int32 {
	if x != nil {
		return x.UpdateIntervalSeconds
	}
	return 0
}

// Location tracking session response
type StartLocationTrackingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLocationTrackingResponse) Reset() {
	*x = StartLocationTrackingResponse{}
	mi := &file_shared_proto_geo_geo_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLocationTrackingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLocationTrackingResponse) ProtoMessage() {}

func (x *StartLocationTrackingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_geo_geo_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLocationTrackingResponse.ProtoReflect.Descriptor instead.
func (*StartLocationTrackingResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_geo_geo_proto_rawDescGZIP(), []int{17}
}

func (x *StartLocationTrackingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartLocationTrackingResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartLocationTrackingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_shared_proto_geo_geo_proto protoreflect.FileDescriptor

const file_shared_proto_geo_geo_proto_rawDesc = "" +
	"\n" +
	"\x1ashared/proto/geo/geo.proto\x12\x03geo\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x01R\baccuracy\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\"\x98\x01\n" +
	"\x0fDistanceRequest\x12%\n" +
	"\x06origin\x18\x01 \x01(\v2\r.geo.LocationR\x06origin\x12/\n" +
	"\vdestination\x18\x02 \x01(\v2\r.geo.LocationR\vdestination\x12-\n" +
	"\x12calculation_method\x18\x03 \x01(\tR\x11calculationMethod\"\xb4\x01\n" +
	"\x10DistanceResponse\x12'\n" +
	"\x0fdistance_meters\x18\x01 \x01(\x01R\x0edistanceMeters\x12\x1f\n" +
	"\vdistance_km\x18\x02 \x01(\x01R\n" +
	"distanceKm\x12'\n" +
	"\x0fbearing_degrees\x18\x03 \x01(\x01R\x0ebearingDegrees\x12-\n" +
	"\x12calculation_method\x18\x04 \x01(\tR\x11calculationMethod\"\xf3\x01\n" +
	"\n" +
	"ETARequest\x12%\n" +
	"\x06origin\x18\x01 \x01(\v2\r.geo.LocationR\x06origin\x12/\n" +
	"\vdestination\x18\x02 \x01(\v2\r.geo.LocationR\vdestination\x12!\n" +
	"\fvehicle_type\x18\x03 \x01(\tR\vvehicleType\x12A\n" +
	"\x0edeparture_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rdepartureTime\x12'\n" +
	"\x0finclude_traffic\x18\x05 \x01(\bR\x0eincludeTraffic\"\xfc\x01\n" +
	"\vETAResponse\x12)\n" +
	"\x10duration_seconds\x18\x01 \x01(\x05R\x0fdurationSeconds\x12'\n" +
	"\x0fdistance_meters\x18\x02 \x01(\x01R\x0edistanceMeters\x12#\n" +
	"\rroute_summary\x18\x03 \x01(\tR\frouteSummary\x12+\n" +
	"\twaypoints\x18\x04 \x03(\v2\r.geo.LocationR\twaypoints\x12G\n" +
	"\x11estimated_arrival\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x10estimatedArrival\"\xbc\x01\n" +
	"\x14NearbyDriversRequest\x12%\n" +
	"\x06center\x18\x01 \x01(\v2\r.geo.LocationR\x06center\x12\x1b\n" +
	"\tradius_km\x18\x02 \x01(\x01R\bradiusKm\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12#\n" +
	"\rvehicle_types\x18\x04 \x03(\tR\fvehicleTypes\x12%\n" +
	"\x0eonly_available\x18\x05 \x01(\bR\ronlyAvailable\"\xfc\x01\n" +
	"\x0eDriverLocation\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tR\tvehicleId\x12)\n" +
	"\blocation\x18\x03 \x01(\v2\r.geo.LocationR\blocation\x120\n" +
	"\x14distance_from_center\x18\x04 \x01(\x01R\x12distanceFromCenter\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fvehicle_type\x18\x06 \x01(\tR\vvehicleType\x12\x16\n" +
	"\x06rating\x18\a \x01(\x01R\x06rating\"\x91\x01\n" +
	"\x15NearbyDriversResponse\x12-\n" +
	"\adrivers\x18\x01 \x03(\v2\x13.geo.DriverLocationR\adrivers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12(\n" +
	"\x10search_radius_km\x18\x03 \x01(\x01R\x0esearchRadiusKm\"\x9c\x01\n" +
	"\x1bUpdateDriverLocationRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12)\n" +
	"\blocation\x18\x02 \x01(\v2\r.geo.LocationR\blocation\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x04 \x01(\tR\tvehicleId\"\x8d\x01\n" +
	"\x1cUpdateDriverLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Y\n" +
	"\x0eGeohashRequest\x12)\n" +
	"\blocation\x18\x01 \x01(\v2\r.geo.LocationR\blocation\x12\x1c\n" +
	"\tprecision\x18\x02 \x01(\x05R\tprecision\"\x9a\x01\n" +
	"\x0fGeohashResponse\x12\x18\n" +
	"\ageohash\x18\x01 \x01(\tR\ageohash\x12%\n" +
	"\x06center\x18\x02 \x01(\v2\r.geo.LocationR\x06center\x12!\n" +
	"\fwidth_meters\x18\x03 \x01(\x01R\vwidthMeters\x12#\n" +
	"\rheight_meters\x18\x04 \x01(\x01R\fheightMeters\"\xdd\x01\n" +
	"\x18RouteOptimizationRequest\x12#\n" +
	"\x05start\x18\x01 \x01(\v2\r.geo.LocationR\x05start\x12+\n" +
	"\twaypoints\x18\x02 \x03(\v2\r.geo.LocationR\twaypoints\x12\x1f\n" +
	"\x03end\x18\x03 \x01(\v2\r.geo.LocationR\x03end\x12+\n" +
	"\x11optimization_type\x18\x04 \x01(\tR\x10optimizationType\x12!\n" +
	"\fvehicle_type\x18\x05 \x01(\tR\vvehicleType\"\xf4\x01\n" +
	"\x19RouteOptimizationResponse\x126\n" +
	"\x0foptimized_route\x18\x01 \x03(\v2\r.geo.LocationR\x0eoptimizedRoute\x12*\n" +
	"\x11total_distance_km\x18\x02 \x01(\x01R\x0ftotalDistanceKm\x12<\n" +
	"\x1aestimated_duration_seconds\x18\x03 \x01(\x05R\x18estimatedDurationSeconds\x125\n" +
	"\x16optimization_algorithm\x18\x04 \x01(\tR\x15optimizationAlgorithm\"w\n" +
	" SubscribeToDriverLocationRequest\x12\x17\n" +
	"\aarea_id\x18\x01 \x01(\tR\x06areaId\x12\x1b\n" +
	"\tradius_km\x18\x02 \x01(\x01R\bradiusKm\x12\x1d\n" +
	"\n" +
	"driver_ids\x18\x03 \x03(\tR\tdriverIds\"\x86\x03\n" +
	"\x13DriverLocationEvent\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12)\n" +
	"\blocation\x18\x02 \x01(\v2\r.geo.LocationR\blocation\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x04 \x01(\tR\tvehicleId\x12\x1b\n" +
	"\tspeed_kmh\x18\x05 \x01(\x01R\bspeedKmh\x12\x18\n" +
	"\aheading\x18\x06 \x01(\x01R\aheading\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12B\n" +
	"\bmetadata\x18\b \x03(\v2&.geo.DriverLocationEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\x1cStartLocationTrackingRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x126\n" +
	"\x17update_interval_seconds\x18\x02 \x01(\x05R\x15updateIntervalSeconds\"r\n" +
	"\x1dStartLocationTrackingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x80\x05\n" +
	"\x11GeospatialService\x12@\n" +
	"\x11CalculateDistance\x12\x14.geo.DistanceRequest\x1a\x15.geo.DistanceResponse\x121\n" +
	"\fCalculateETA\x12\x0f.geo.ETARequest\x1a\x10.geo.ETAResponse\x12J\n" +
	"\x11FindNearbyDrivers\x12\x19.geo.NearbyDriversRequest\x1a\x1a.geo.NearbyDriversResponse\x12[\n" +
	"\x14UpdateDriverLocation\x12 .geo.UpdateDriverLocationRequest\x1a!.geo.UpdateDriverLocationResponse\x12<\n" +
	"\x0fGenerateGeohash\x12\x13.geo.GeohashRequest\x1a\x14.geo.GeohashResponse\x12N\n" +
	"\rOptimizeRoute\x12\x1d.geo.RouteOptimizationRequest\x1a\x1e.geo.RouteOptimizationResponse\x12_\n" +
	"\x1aSubscribeToDriverLocations\x12%.geo.SubscribeToDriverLocationRequest\x1a\x18.geo.DriverLocationEvent0\x01\x12^\n" +
	"\x15StartLocationTracking\x12!.geo.StartLocationTrackingRequest\x1a\".geo.StartLocationTrackingResponseB6Z4github.com/rideshare-platform/shared/proto/geo;geopbb\x06proto3"

var (
	file_shared_proto_geo_geo_proto_rawDescOnce sync.Once
	file_shared_proto_geo_geo_proto_rawDescData []byte
)

func file_shared_proto_geo_geo_proto_rawDescGZIP() []byte {
	file_shared_proto_geo_geo_proto_rawDescOnce.Do(func() {
		file_shared_proto_geo_geo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_geo_geo_proto_rawDesc), len(file_shared_proto_geo_geo_proto_rawDesc)))
	})
	return file_shared_proto_geo_geo_proto_rawDescData
}

var file_shared_proto_geo_geo_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_shared_proto_geo_geo_proto_goTypes = []any{
	(*Location)(nil),                         // 0: geo.Location
	(*DistanceRequest)(nil),                  // 1: geo.DistanceRequest
	(*DistanceResponse)(nil),                 // 2: geo.DistanceResponse
	(*ETARequest)(nil),                       // 3: geo.ETARequest
	(*ETAResponse)(nil),                      // 4: geo.ETAResponse
	(*NearbyDriversRequest)(nil),             // 5: geo.NearbyDriversRequest
	(*DriverLocation)(nil),                   // 6: geo.DriverLocation
	(*NearbyDriversResponse)(nil),            // 7: geo.NearbyDriversResponse
	(*UpdateDriverLocationRequest)(nil),      // 8: geo.UpdateDriverLocationRequest
	(*UpdateDriverLocationResponse)(nil),     // 9: geo.UpdateDriverLocationResponse
	(*GeohashRequest)(nil),                   // 10: geo.GeohashRequest
	(*GeohashResponse)(nil),                  // 11: geo.GeohashResponse
	(*RouteOptimizationRequest)(nil),         // 12: geo.RouteOptimizationRequest
	(*RouteOptimizationResponse)(nil),        // 13: geo.RouteOptimizationResponse
	(*SubscribeToDriverLocationRequest)(nil), // 14: geo.SubscribeToDriverLocationRequest
	(*DriverLocationEvent)(nil),              // 15: geo.DriverLocationEvent
	(*StartLocationTrackingRequest)(nil),     // 16: geo.StartLocationTrackingRequest
	(*StartLocationTrackingResponse)(nil),    // 17: geo.StartLocationTrackingResponse
	nil,                                      // 18: geo.DriverLocationEvent.MetadataEntry
	(*timestamppb.Timestamp)(nil),            // 19: google.protobuf.Timestamp
}
var file_shared_proto_geo_geo_proto_depIdxs = []int32{
	19, // 0: geo.Location.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: geo.DistanceRequest.origin:type_name -> geo.Location
	0,  // 2: geo.DistanceRequest.destination:type_name -> geo.Location
	0,  // 3: geo.ETARequest.origin:type_name -> geo.Location
	0,  // 4: geo.ETARequest.destination:type_name -> geo.Location
	19, // 5: geo.ETARequest.departure_time:type_name -> google.protobuf.Timestamp
	0,  // 6: geo.ETAResponse.waypoints:type_name -> geo.Location
	19, // 7: geo.ETAResponse.estimated_arrival:type_name -> google.protobuf.Timestamp
	0,  // 8: geo.NearbyDriversRequest.center:type_name -> geo.Location
	0,  // 9: geo.DriverLocation.location:type_name -> geo.Location
	6,  // 10: geo.NearbyDriversResponse.drivers:type_name -> geo.DriverLocation
	0,  // 11: geo.UpdateDriverLocationRequest.location:type_name -> geo.Location
	19, // 12: geo.UpdateDriverLocationResponse.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 13: geo.GeohashRequest.location:type_name -> geo.Location
	0,  // 14: geo.GeohashResponse.center:type_name -> geo.Location
	0,  // 15: geo.RouteOptimizationRequest.start:type_name -> geo.Location
	0,  // 16: geo.RouteOptimizationRequest.waypoints:type_name -> geo.Location
	0,  // 17: geo.RouteOptimizationRequest.end:type_name -> geo.Location
	0,  // 18: geo.RouteOptimizationResponse.optimized_route:type_name -> geo.Location
	0,  // 19: geo.DriverLocationEvent.location:type_name -> geo.Location
	19, // 20: geo.DriverLocationEvent.timestamp:type_name -> google.protobuf.Timestamp
	18, // 21: geo.DriverLocationEvent.metadata:type_name -> geo.DriverLocationEvent.MetadataEntry
	1,  // 22: geo.GeospatialService.CalculateDistance:input_type -> geo.DistanceRequest
	3,  // 23: geo.GeospatialService.CalculateETA:input_type -> geo.ETARequest
	5,  // 24: geo.GeospatialService.FindNearbyDrivers:input_type -> geo.NearbyDriversRequest
	8,  // 25: geo.GeospatialService.UpdateDriverLocation:input_type -> geo.UpdateDriverLocationRequest
	10, // 26: geo.GeospatialService.GenerateGeohash:input_type -> geo.GeohashRequest
	12, // 27: geo.GeospatialService.OptimizeRoute:input_type -> geo.RouteOptimizationRequest
	14, // 28: geo.GeospatialService.SubscribeToDriverLocations:input_type -> geo.SubscribeToDriverLocationRequest
	16, // 29: geo.GeospatialService.StartLocationTracking:input_type -> geo.StartLocationTrackingRequest
	2,  // 30: geo.GeospatialService.CalculateDistance:output_type -> geo.DistanceResponse
	4,  // 31: geo.GeospatialService.CalculateETA:output_type -> geo.ETAResponse
	7,  // 32: geo.GeospatialService.FindNearbyDrivers:output_type -> geo.NearbyDriversResponse
	9,  // 33: geo.GeospatialService.UpdateDriverLocation:output_type -> geo.UpdateDriverLocationResponse
	11, // 34: geo.GeospatialService.GenerateGeohash:output_type -> geo.GeohashResponse
	13, // 35: geo.GeospatialService.OptimizeRoute:output_type -> geo.RouteOptimizationResponse
	15, // 36: geo.GeospatialService.SubscribeToDriverLocations:output_type -> geo.DriverLocationEvent
	17, // 37: geo.GeospatialService.StartLocationTracking:output_type -> geo.StartLocationTrackingResponse
	30, // [30:38] is the sub-list for method output_type
	22, // [22:30] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_shared_proto_geo_geo_proto_init() }
func file_shared_proto_geo_geo_proto_init() {
	if File_shared_proto_geo_geo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_geo_geo_proto_rawDesc), len(file_shared_proto_geo_geo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_geo_geo_proto_goTypes,
		DependencyIndexes: file_shared_proto_geo_geo_proto_depIdxs,
		MessageInfos:      file_shared_proto_geo_geo_proto_msgTypes,
	}.Build()
	File_shared_proto_geo_geo_proto = out.File
	file_shared_proto_geo_geo_proto_goTypes = nil
	file_shared_proto_geo_geo_proto_depIdxs = nil
}
