apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: rideshare-platform
  labels:
    app: user-service
    component: microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        component: microservice
    spec:
      containers:
      - name: user-service
        image: rideshare/user-service:latest
        ports:
        - containerPort: 9084
        envFrom:
        - configMapRef:
            name: rideshare-config
        - secretRef:
            name: rideshare-secrets
        env:
        - name: HTTP_PORT
          value: "9084"
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: rideshare-config
              key: POSTGRES_HOST
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /ready
            port: 9084
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 9084
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: rideshare-platform
  labels:
    app: user-service
    component: microservice
spec:
  selector:
    app: user-service
  ports:
  - port: 9084
    targetPort: 9084
    name: http
  type: ClusterIP
