apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-service
  namespace: rideshare-platform
  labels:
    app: vehicle-service
    component: microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vehicle-service
  template:
    metadata:
      labels:
        app: vehicle-service
        component: microservice
    spec:
      containers:
      - name: vehicle-service
        image: rideshare/vehicle-service:latest
        ports:
        - containerPort: 9083
        envFrom:
        - configMapRef:
            name: rideshare-config
        - secretRef:
            name: rideshare-secrets
        env:
        - name: HTTP_PORT
          value: "9083"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /ready
            port: 9083
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 9083
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
  namespace: rideshare-platform
  labels:
    app: vehicle-service
    component: microservice
spec:
  selector:
    app: vehicle-service
  ports:
  - port: 9083
    targetPort: 9083
    name: http
  type: ClusterIP
