// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User roles
type UserRole int32

const (
	UserRole_UNKNOWN_ROLE UserRole = 0
	UserRole_RIDER        UserRole = 1
	UserRole_DRIVER       UserRole = 2
	UserRole_ADMIN        UserRole = 3
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "UNKNOWN_ROLE",
		1: "RIDER",
		2: "DRIVER",
		3: "ADMIN",
	}
	UserRole_value = map[string]int32{
		"UNKNOWN_ROLE": 0,
		"RIDER":        1,
		"DRIVER":       2,
		"ADMIN":        3,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_user_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_proto_user_user_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{0}
}

// User status
type UserStatus int32

const (
	UserStatus_UNKNOWN_STATUS UserStatus = 0
	UserStatus_ACTIVE         UserStatus = 1
	UserStatus_INACTIVE       UserStatus = 2
	UserStatus_SUSPENDED      UserStatus = 3
	UserStatus_BANNED         UserStatus = 4
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "UNKNOWN_STATUS",
		1: "ACTIVE",
		2: "INACTIVE",
		3: "SUSPENDED",
		4: "BANNED",
	}
	UserStatus_value = map[string]int32{
		"UNKNOWN_STATUS": 0,
		"ACTIVE":         1,
		"INACTIVE":       2,
		"SUSPENDED":      3,
		"BANNED":         4,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_user_proto_enumTypes[1].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_proto_user_user_proto_enumTypes[1]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{1}
}

type DriverStatus int32

const (
	DriverStatus_UNKNOWN_DRIVER_STATUS DriverStatus = 0
	DriverStatus_OFFLINE               DriverStatus = 1
	DriverStatus_ONLINE                DriverStatus = 2
	DriverStatus_ON_TRIP               DriverStatus = 3
	DriverStatus_BREAK                 DriverStatus = 4
)

// Enum value maps for DriverStatus.
var (
	DriverStatus_name = map[int32]string{
		0: "UNKNOWN_DRIVER_STATUS",
		1: "OFFLINE",
		2: "ONLINE",
		3: "ON_TRIP",
		4: "BREAK",
	}
	DriverStatus_value = map[string]int32{
		"UNKNOWN_DRIVER_STATUS": 0,
		"OFFLINE":               1,
		"ONLINE":                2,
		"ON_TRIP":               3,
		"BREAK":                 4,
	}
)

func (x DriverStatus) Enum() *DriverStatus {
	p := new(DriverStatus)
	*p = x
	return p
}

func (x DriverStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriverStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_user_proto_enumTypes[2].Descriptor()
}

func (DriverStatus) Type() protoreflect.EnumType {
	return &file_proto_user_user_proto_enumTypes[2]
}

func (x DriverStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriverStatus.Descriptor instead.
func (DriverStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{2}
}

// Location represents a geographical coordinate (duplicated for independence)
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *Location) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// User represents a platform user (rider or driver)
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role          UserRole               `protobuf:"varint,6,opt,name=role,proto3,enum=user.UserRole" json:"role,omitempty"`
	Status        UserStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=user.UserStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Profile       *UserProfile           `protobuf:"bytes,10,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_UNKNOWN_ROLE
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_UNKNOWN_STATUS
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// Extended user profile information
type UserProfile struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AvatarUrl         string                 `protobuf:"bytes,1,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	DateOfBirth       string                 `protobuf:"bytes,2,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender            string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	PreferredLanguage string                 `protobuf:"bytes,4,opt,name=preferred_language,json=preferredLanguage,proto3" json:"preferred_language,omitempty"`
	Rating            float64                `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`
	TotalTrips        int32                  `protobuf:"varint,6,opt,name=total_trips,json=totalTrips,proto3" json:"total_trips,omitempty"`
	EmailVerified     bool                   `protobuf:"varint,7,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	PhoneVerified     bool                   `protobuf:"varint,8,opt,name=phone_verified,json=phoneVerified,proto3" json:"phone_verified,omitempty"`
	Preferences       *UserPreferences       `protobuf:"bytes,9,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_proto_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserProfile) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *UserProfile) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UserProfile) GetPreferredLanguage() string {
	if x != nil {
		return x.PreferredLanguage
	}
	return ""
}

func (x *UserProfile) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UserProfile) GetTotalTrips() int32 {
	if x != nil {
		return x.TotalTrips
	}
	return 0
}

func (x *UserProfile) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *UserProfile) GetPhoneVerified() bool {
	if x != nil {
		return x.PhoneVerified
	}
	return false
}

func (x *UserProfile) GetPreferences() *UserPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

// User preferences
type UserPreferences struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AllowNotifications    bool                   `protobuf:"varint,1,opt,name=allow_notifications,json=allowNotifications,proto3" json:"allow_notifications,omitempty"`
	ShareLocation         bool                   `protobuf:"varint,2,opt,name=share_location,json=shareLocation,proto3" json:"share_location,omitempty"`
	DefaultPaymentMethod  string                 `protobuf:"bytes,3,opt,name=default_payment_method,json=defaultPaymentMethod,proto3" json:"default_payment_method,omitempty"`
	QuietRides            bool                   `protobuf:"varint,4,opt,name=quiet_rides,json=quietRides,proto3" json:"quiet_rides,omitempty"`
	AccessibilityFeatures bool                   `protobuf:"varint,5,opt,name=accessibility_features,json=accessibilityFeatures,proto3" json:"accessibility_features,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserPreferences) Reset() {
	*x = UserPreferences{}
	mi := &file_proto_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferences) ProtoMessage() {}

func (x *UserPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferences.ProtoReflect.Descriptor instead.
func (*UserPreferences) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserPreferences) GetAllowNotifications() bool {
	if x != nil {
		return x.AllowNotifications
	}
	return false
}

func (x *UserPreferences) GetShareLocation() bool {
	if x != nil {
		return x.ShareLocation
	}
	return false
}

func (x *UserPreferences) GetDefaultPaymentMethod() string {
	if x != nil {
		return x.DefaultPaymentMethod
	}
	return ""
}

func (x *UserPreferences) GetQuietRides() bool {
	if x != nil {
		return x.QuietRides
	}
	return false
}

func (x *UserPreferences) GetAccessibilityFeatures() bool {
	if x != nil {
		return x.AccessibilityFeatures
	}
	return false
}

// Requests and responses
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role          UserRole               `protobuf:"varint,5,opt,name=role,proto3,enum=user.UserRole" json:"role,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserRequest) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_UNKNOWN_ROLE
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_proto_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateUserResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	UpdateFields  []string               `protobuf:"bytes,3,rep,name=update_fields,json=updateFields,proto3" json:"update_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserRequest) GetUpdateFields() []string {
	if x != nil {
		return x.UpdateFields
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_proto_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          UserRole               `protobuf:"varint,1,opt,name=role,proto3,enum=user.UserRole" json:"role,omitempty"`
	Status        UserStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=user.UserStatus" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *ListUsersRequest) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_UNKNOWN_ROLE
}

func (x *ListUsersRequest) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_UNKNOWN_STATUS
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_proto_user_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{11}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListUsersResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// Driver-specific messages
type Driver struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LicenseNumber   string                 `protobuf:"bytes,2,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	LicenseExpiry   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=license_expiry,json=licenseExpiry,proto3" json:"license_expiry,omitempty"`
	Status          DriverStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=user.DriverStatus" json:"status,omitempty"`
	CurrentLocation *Location              `protobuf:"bytes,5,opt,name=current_location,json=currentLocation,proto3" json:"current_location,omitempty"`
	Rating          float64                `protobuf:"fixed64,6,opt,name=rating,proto3" json:"rating,omitempty"`
	TotalTrips      int32                  `protobuf:"varint,7,opt,name=total_trips,json=totalTrips,proto3" json:"total_trips,omitempty"`
	VehicleId       string                 `protobuf:"bytes,8,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	IsAvailable     bool                   `protobuf:"varint,9,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	LastActive      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Driver) Reset() {
	*x = Driver{}
	mi := &file_proto_user_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{12}
}

func (x *Driver) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Driver) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *Driver) GetLicenseExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.LicenseExpiry
	}
	return nil
}

func (x *Driver) GetStatus() DriverStatus {
	if x != nil {
		return x.Status
	}
	return DriverStatus_UNKNOWN_DRIVER_STATUS
}

func (x *Driver) GetCurrentLocation() *Location {
	if x != nil {
		return x.CurrentLocation
	}
	return nil
}

func (x *Driver) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Driver) GetTotalTrips() int32 {
	if x != nil {
		return x.TotalTrips
	}
	return 0
}

func (x *Driver) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *Driver) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *Driver) GetLastActive() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActive
	}
	return nil
}

type UpdateDriverLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Location      *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Status        DriverStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=user.DriverStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationRequest) Reset() {
	*x = UpdateDriverLocationRequest{}
	mi := &file_proto_user_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationRequest) ProtoMessage() {}

func (x *UpdateDriverLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateDriverLocationRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateDriverLocationRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *UpdateDriverLocationRequest) GetStatus() DriverStatus {
	if x != nil {
		return x.Status
	}
	return DriverStatus_UNKNOWN_DRIVER_STATUS
}

type UpdateDriverLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationResponse) Reset() {
	*x = UpdateDriverLocationResponse{}
	mi := &file_proto_user_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationResponse) ProtoMessage() {}

func (x *UpdateDriverLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateDriverLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDriverLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverRequest) Reset() {
	*x = GetDriverRequest{}
	mi := &file_proto_user_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverRequest) ProtoMessage() {}

func (x *GetDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverRequest.ProtoReflect.Descriptor instead.
func (*GetDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{15}
}

func (x *GetDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GetDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        *Driver                `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverResponse) Reset() {
	*x = GetDriverResponse{}
	mi := &file_proto_user_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverResponse) ProtoMessage() {}

func (x *GetDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverResponse.ProtoReflect.Descriptor instead.
func (*GetDriverResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_user_proto_rawDescGZIP(), []int{16}
}

func (x *GetDriverResponse) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

func (x *GetDriverResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_proto_user_user_proto protoreflect.FileDescriptor

const file_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"\x15proto/user/user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x01R\baccuracy\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\"\xef\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\"\n" +
	"\x04role\x18\x06 \x01(\x0e2\x0e.user.UserRoleR\x04role\x12(\n" +
	"\x06status\x18\a \x01(\x0e2\x10.user.UserStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12+\n" +
	"\aprofile\x18\n" +
	" \x01(\v2\x11.user.UserProfileR\aprofile\"\xd7\x02\n" +
	"\vUserProfile\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x01 \x01(\tR\tavatarUrl\x12\"\n" +
	"\rdate_of_birth\x18\x02 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12-\n" +
	"\x12preferred_language\x18\x04 \x01(\tR\x11preferredLanguage\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x01R\x06rating\x12\x1f\n" +
	"\vtotal_trips\x18\x06 \x01(\x05R\n" +
	"totalTrips\x12%\n" +
	"\x0eemail_verified\x18\a \x01(\bR\remailVerified\x12%\n" +
	"\x0ephone_verified\x18\b \x01(\bR\rphoneVerified\x127\n" +
	"\vpreferences\x18\t \x01(\v2\x15.user.UserPreferencesR\vpreferences\"\xf7\x01\n" +
	"\x0fUserPreferences\x12/\n" +
	"\x13allow_notifications\x18\x01 \x01(\bR\x12allowNotifications\x12%\n" +
	"\x0eshare_location\x18\x02 \x01(\bR\rshareLocation\x124\n" +
	"\x16default_payment_method\x18\x03 \x01(\tR\x14defaultPaymentMethod\x12\x1f\n" +
	"\vquiet_rides\x18\x04 \x01(\bR\n" +
	"quietRides\x125\n" +
	"\x16accessibility_features\x18\x05 \x01(\bR\x15accessibilityFeatures\"\xbb\x01\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\"\n" +
	"\x04role\x18\x05 \x01(\x0e2\x0e.user.UserRoleR\x04role\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\"\x80\x01\n" +
	"\x12CreateUserResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x0fGetUserResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"h\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\x04user\x18\x02 \x01(\v2\n" +
	".user.UserR\x04user\x12#\n" +
	"\rupdate_fields\x18\x03 \x03(\tR\fupdateFields\"h\n" +
	"\x12UpdateUserResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8e\x01\n" +
	"\x10ListUsersRequest\x12\"\n" +
	"\x04role\x18\x01 \x01(\x0e2\x0e.user.UserRoleR\x04role\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.user.UserStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"q\n" +
	"\x11ListUsersResponse\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".user.UserR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\xaa\x03\n" +
	"\x06Driver\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0elicense_number\x18\x02 \x01(\tR\rlicenseNumber\x12A\n" +
	"\x0elicense_expiry\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rlicenseExpiry\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.user.DriverStatusR\x06status\x129\n" +
	"\x10current_location\x18\x05 \x01(\v2\x0e.user.LocationR\x0fcurrentLocation\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x01R\x06rating\x12\x1f\n" +
	"\vtotal_trips\x18\a \x01(\x05R\n" +
	"totalTrips\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\b \x01(\tR\tvehicleId\x12!\n" +
	"\fis_available\x18\t \x01(\bR\visAvailable\x12;\n" +
	"\vlast_active\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastActive\"\x92\x01\n" +
	"\x1bUpdateDriverLocationRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12*\n" +
	"\blocation\x18\x02 \x01(\v2\x0e.user.LocationR\blocation\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.user.DriverStatusR\x06status\"R\n" +
	"\x1cUpdateDriverLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x10GetDriverRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\"O\n" +
	"\x11GetDriverResponse\x12$\n" +
	"\x06driver\x18\x01 \x01(\v2\f.user.DriverR\x06driver\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found*>\n" +
	"\bUserRole\x12\x10\n" +
	"\fUNKNOWN_ROLE\x10\x00\x12\t\n" +
	"\x05RIDER\x10\x01\x12\n" +
	"\n" +
	"\x06DRIVER\x10\x02\x12\t\n" +
	"\x05ADMIN\x10\x03*U\n" +
	"\n" +
	"UserStatus\x12\x12\n" +
	"\x0eUNKNOWN_STATUS\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bINACTIVE\x10\x02\x12\r\n" +
	"\tSUSPENDED\x10\x03\x12\n" +
	"\n" +
	"\x06BANNED\x10\x04*Z\n" +
	"\fDriverStatus\x12\x19\n" +
	"\x15UNKNOWN_DRIVER_STATUS\x10\x00\x12\v\n" +
	"\aOFFLINE\x10\x01\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x02\x12\v\n" +
	"\aON_TRIP\x10\x03\x12\t\n" +
	"\x05BREAK\x10\x042\xa2\x03\n" +
	"\vUserService\x12?\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\x126\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12?\n" +
	"\n" +
	"UpdateUser\x12\x17.user.UpdateUserRequest\x1a\x18.user.UpdateUserResponse\x12<\n" +
	"\tListUsers\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponse\x12]\n" +
	"\x14UpdateDriverLocation\x12!.user.UpdateDriverLocationRequest\x1a\".user.UpdateDriverLocationResponse\x12<\n" +
	"\tGetDriver\x12\x16.user.GetDriverRequest\x1a\x17.user.GetDriverResponseB1Z/github.com/rideshare-platform/shared/proto/userb\x06proto3"

var (
	file_proto_user_user_proto_rawDescOnce sync.Once
	file_proto_user_user_proto_rawDescData []byte
)

func file_proto_user_user_proto_rawDescGZIP() []byte {
	file_proto_user_user_proto_rawDescOnce.Do(func() {
		file_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_user_proto_rawDesc), len(file_proto_user_user_proto_rawDesc)))
	})
	return file_proto_user_user_proto_rawDescData
}

var file_proto_user_user_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_user_user_proto_goTypes = []any{
	(UserRole)(0),                        // 0: user.UserRole
	(UserStatus)(0),                      // 1: user.UserStatus
	(DriverStatus)(0),                    // 2: user.DriverStatus
	(*Location)(nil),                     // 3: user.Location
	(*User)(nil),                         // 4: user.User
	(*UserProfile)(nil),                  // 5: user.UserProfile
	(*UserPreferences)(nil),              // 6: user.UserPreferences
	(*CreateUserRequest)(nil),            // 7: user.CreateUserRequest
	(*CreateUserResponse)(nil),           // 8: user.CreateUserResponse
	(*GetUserRequest)(nil),               // 9: user.GetUserRequest
	(*GetUserResponse)(nil),              // 10: user.GetUserResponse
	(*UpdateUserRequest)(nil),            // 11: user.UpdateUserRequest
	(*UpdateUserResponse)(nil),           // 12: user.UpdateUserResponse
	(*ListUsersRequest)(nil),             // 13: user.ListUsersRequest
	(*ListUsersResponse)(nil),            // 14: user.ListUsersResponse
	(*Driver)(nil),                       // 15: user.Driver
	(*UpdateDriverLocationRequest)(nil),  // 16: user.UpdateDriverLocationRequest
	(*UpdateDriverLocationResponse)(nil), // 17: user.UpdateDriverLocationResponse
	(*GetDriverRequest)(nil),             // 18: user.GetDriverRequest
	(*GetDriverResponse)(nil),            // 19: user.GetDriverResponse
	(*timestamppb.Timestamp)(nil),        // 20: google.protobuf.Timestamp
}
var file_proto_user_user_proto_depIdxs = []int32{
	20, // 0: user.Location.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: user.User.role:type_name -> user.UserRole
	1,  // 2: user.User.status:type_name -> user.UserStatus
	20, // 3: user.User.created_at:type_name -> google.protobuf.Timestamp
	20, // 4: user.User.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 5: user.User.profile:type_name -> user.UserProfile
	6,  // 6: user.UserProfile.preferences:type_name -> user.UserPreferences
	0,  // 7: user.CreateUserRequest.role:type_name -> user.UserRole
	4,  // 8: user.CreateUserResponse.user:type_name -> user.User
	4,  // 9: user.GetUserResponse.user:type_name -> user.User
	4,  // 10: user.UpdateUserRequest.user:type_name -> user.User
	4,  // 11: user.UpdateUserResponse.user:type_name -> user.User
	0,  // 12: user.ListUsersRequest.role:type_name -> user.UserRole
	1,  // 13: user.ListUsersRequest.status:type_name -> user.UserStatus
	4,  // 14: user.ListUsersResponse.users:type_name -> user.User
	20, // 15: user.Driver.license_expiry:type_name -> google.protobuf.Timestamp
	2,  // 16: user.Driver.status:type_name -> user.DriverStatus
	3,  // 17: user.Driver.current_location:type_name -> user.Location
	20, // 18: user.Driver.last_active:type_name -> google.protobuf.Timestamp
	3,  // 19: user.UpdateDriverLocationRequest.location:type_name -> user.Location
	2,  // 20: user.UpdateDriverLocationRequest.status:type_name -> user.DriverStatus
	15, // 21: user.GetDriverResponse.driver:type_name -> user.Driver
	7,  // 22: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	9,  // 23: user.UserService.GetUser:input_type -> user.GetUserRequest
	11, // 24: user.UserService.UpdateUser:input_type -> user.UpdateUserRequest
	13, // 25: user.UserService.ListUsers:input_type -> user.ListUsersRequest
	16, // 26: user.UserService.UpdateDriverLocation:input_type -> user.UpdateDriverLocationRequest
	18, // 27: user.UserService.GetDriver:input_type -> user.GetDriverRequest
	8,  // 28: user.UserService.CreateUser:output_type -> user.CreateUserResponse
	10, // 29: user.UserService.GetUser:output_type -> user.GetUserResponse
	12, // 30: user.UserService.UpdateUser:output_type -> user.UpdateUserResponse
	14, // 31: user.UserService.ListUsers:output_type -> user.ListUsersResponse
	17, // 32: user.UserService.UpdateDriverLocation:output_type -> user.UpdateDriverLocationResponse
	19, // 33: user.UserService.GetDriver:output_type -> user.GetDriverResponse
	28, // [28:34] is the sub-list for method output_type
	22, // [22:28] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_user_user_proto_init() }
func file_proto_user_user_proto_init() {
	if File_proto_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_user_proto_rawDesc), len(file_proto_user_user_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_user_proto_goTypes,
		DependencyIndexes: file_proto_user_user_proto_depIdxs,
		EnumInfos:         file_proto_user_user_proto_enumTypes,
		MessageInfos:      file_proto_user_user_proto_msgTypes,
	}.Build()
	File_proto_user_user_proto = out.File
	file_proto_user_user_proto_goTypes = nil
	file_proto_user_user_proto_depIdxs = nil
}
