// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: pricing.proto

package pricing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Location represents a geographical coordinate
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_pricing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Pricing estimate
type PriceEstimate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseFare        float64                `protobuf:"fixed64,2,opt,name=base_fare,json=baseFare,proto3" json:"base_fare,omitempty"`
	DistanceFare    float64                `protobuf:"fixed64,3,opt,name=distance_fare,json=distanceFare,proto3" json:"distance_fare,omitempty"`
	TimeFare        float64                `protobuf:"fixed64,4,opt,name=time_fare,json=timeFare,proto3" json:"time_fare,omitempty"`
	SurgeMultiplier float64                `protobuf:"fixed64,5,opt,name=surge_multiplier,json=surgeMultiplier,proto3" json:"surge_multiplier,omitempty"`
	SurgeAmount     float64                `protobuf:"fixed64,6,opt,name=surge_amount,json=surgeAmount,proto3" json:"surge_amount,omitempty"`
	DiscountAmount  float64                `protobuf:"fixed64,7,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	TotalAmount     float64                `protobuf:"fixed64,8,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Currency        string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	Breakdown       *PricingBreakdown      `protobuf:"bytes,10,opt,name=breakdown,proto3" json:"breakdown,omitempty"`
	ValidUntil      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PriceEstimate) Reset() {
	*x = PriceEstimate{}
	mi := &file_pricing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceEstimate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceEstimate) ProtoMessage() {}

func (x *PriceEstimate) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceEstimate.ProtoReflect.Descriptor instead.
func (*PriceEstimate) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{1}
}

func (x *PriceEstimate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PriceEstimate) GetBaseFare() float64 {
	if x != nil {
		return x.BaseFare
	}
	return 0
}

func (x *PriceEstimate) GetDistanceFare() float64 {
	if x != nil {
		return x.DistanceFare
	}
	return 0
}

func (x *PriceEstimate) GetTimeFare() float64 {
	if x != nil {
		return x.TimeFare
	}
	return 0
}

func (x *PriceEstimate) GetSurgeMultiplier() float64 {
	if x != nil {
		return x.SurgeMultiplier
	}
	return 0
}

func (x *PriceEstimate) GetSurgeAmount() float64 {
	if x != nil {
		return x.SurgeAmount
	}
	return 0
}

func (x *PriceEstimate) GetDiscountAmount() float64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *PriceEstimate) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *PriceEstimate) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PriceEstimate) GetBreakdown() *PricingBreakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

func (x *PriceEstimate) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

// Detailed pricing breakdown
type PricingBreakdown struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BaseRate        float64                `protobuf:"fixed64,1,opt,name=base_rate,json=baseRate,proto3" json:"base_rate,omitempty"`
	PerKmRate       float64                `protobuf:"fixed64,2,opt,name=per_km_rate,json=perKmRate,proto3" json:"per_km_rate,omitempty"`
	PerMinuteRate   float64                `protobuf:"fixed64,3,opt,name=per_minute_rate,json=perMinuteRate,proto3" json:"per_minute_rate,omitempty"`
	DistanceKm      float64                `protobuf:"fixed64,4,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,5,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	BookingFee      float64                `protobuf:"fixed64,6,opt,name=booking_fee,json=bookingFee,proto3" json:"booking_fee,omitempty"`
	ServiceFee      float64                `protobuf:"fixed64,7,opt,name=service_fee,json=serviceFee,proto3" json:"service_fee,omitempty"`
	Taxes           float64                `protobuf:"fixed64,8,opt,name=taxes,proto3" json:"taxes,omitempty"`
	Tolls           float64                `protobuf:"fixed64,9,opt,name=tolls,proto3" json:"tolls,omitempty"`
	Discounts       []*AppliedDiscount     `protobuf:"bytes,10,rep,name=discounts,proto3" json:"discounts,omitempty"`
	SurgeInfo       *SurgeInfo             `protobuf:"bytes,11,opt,name=surge_info,json=surgeInfo,proto3" json:"surge_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PricingBreakdown) Reset() {
	*x = PricingBreakdown{}
	mi := &file_pricing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingBreakdown) ProtoMessage() {}

func (x *PricingBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingBreakdown.ProtoReflect.Descriptor instead.
func (*PricingBreakdown) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{2}
}

func (x *PricingBreakdown) GetBaseRate() float64 {
	if x != nil {
		return x.BaseRate
	}
	return 0
}

func (x *PricingBreakdown) GetPerKmRate() float64 {
	if x != nil {
		return x.PerKmRate
	}
	return 0
}

func (x *PricingBreakdown) GetPerMinuteRate() float64 {
	if x != nil {
		return x.PerMinuteRate
	}
	return 0
}

func (x *PricingBreakdown) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *PricingBreakdown) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *PricingBreakdown) GetBookingFee() float64 {
	if x != nil {
		return x.BookingFee
	}
	return 0
}

func (x *PricingBreakdown) GetServiceFee() float64 {
	if x != nil {
		return x.ServiceFee
	}
	return 0
}

func (x *PricingBreakdown) GetTaxes() float64 {
	if x != nil {
		return x.Taxes
	}
	return 0
}

func (x *PricingBreakdown) GetTolls() float64 {
	if x != nil {
		return x.Tolls
	}
	return 0
}

func (x *PricingBreakdown) GetDiscounts() []*AppliedDiscount {
	if x != nil {
		return x.Discounts
	}
	return nil
}

func (x *PricingBreakdown) GetSurgeInfo() *SurgeInfo {
	if x != nil {
		return x.SurgeInfo
	}
	return nil
}

// Applied discount information
type AppliedDiscount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "percentage", "fixed_amount", "first_ride"
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	AmountSaved   float64                `protobuf:"fixed64,5,opt,name=amount_saved,json=amountSaved,proto3" json:"amount_saved,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppliedDiscount) Reset() {
	*x = AppliedDiscount{}
	mi := &file_pricing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppliedDiscount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppliedDiscount) ProtoMessage() {}

func (x *AppliedDiscount) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppliedDiscount.ProtoReflect.Descriptor instead.
func (*AppliedDiscount) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{3}
}

func (x *AppliedDiscount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppliedDiscount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppliedDiscount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AppliedDiscount) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AppliedDiscount) GetAmountSaved() float64 {
	if x != nil {
		return x.AmountSaved
	}
	return 0
}

func (x *AppliedDiscount) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Surge pricing information
type SurgeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Multiplier    float64                `protobuf:"fixed64,2,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	ZoneId        string                 `protobuf:"bytes,6,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurgeInfo) Reset() {
	*x = SurgeInfo{}
	mi := &file_pricing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurgeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurgeInfo) ProtoMessage() {}

func (x *SurgeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurgeInfo.ProtoReflect.Descriptor instead.
func (*SurgeInfo) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{4}
}

func (x *SurgeInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *SurgeInfo) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *SurgeInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SurgeInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SurgeInfo) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *SurgeInfo) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

// Dynamic pricing factors
type PricingFactors struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DemandMultiplier    float64                `protobuf:"fixed64,1,opt,name=demand_multiplier,json=demandMultiplier,proto3" json:"demand_multiplier,omitempty"`
	SupplyMultiplier    float64                `protobuf:"fixed64,2,opt,name=supply_multiplier,json=supplyMultiplier,proto3" json:"supply_multiplier,omitempty"`
	WeatherMultiplier   float64                `protobuf:"fixed64,3,opt,name=weather_multiplier,json=weatherMultiplier,proto3" json:"weather_multiplier,omitempty"`
	EventMultiplier     float64                `protobuf:"fixed64,4,opt,name=event_multiplier,json=eventMultiplier,proto3" json:"event_multiplier,omitempty"`
	TimeOfDayMultiplier float64                `protobuf:"fixed64,5,opt,name=time_of_day_multiplier,json=timeOfDayMultiplier,proto3" json:"time_of_day_multiplier,omitempty"`
	CustomFactors       map[string]float64     `protobuf:"bytes,6,rep,name=custom_factors,json=customFactors,proto3" json:"custom_factors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PricingFactors) Reset() {
	*x = PricingFactors{}
	mi := &file_pricing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingFactors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingFactors) ProtoMessage() {}

func (x *PricingFactors) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingFactors.ProtoReflect.Descriptor instead.
func (*PricingFactors) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{5}
}

func (x *PricingFactors) GetDemandMultiplier() float64 {
	if x != nil {
		return x.DemandMultiplier
	}
	return 0
}

func (x *PricingFactors) GetSupplyMultiplier() float64 {
	if x != nil {
		return x.SupplyMultiplier
	}
	return 0
}

func (x *PricingFactors) GetWeatherMultiplier() float64 {
	if x != nil {
		return x.WeatherMultiplier
	}
	return 0
}

func (x *PricingFactors) GetEventMultiplier() float64 {
	if x != nil {
		return x.EventMultiplier
	}
	return 0
}

func (x *PricingFactors) GetTimeOfDayMultiplier() float64 {
	if x != nil {
		return x.TimeOfDayMultiplier
	}
	return 0
}

func (x *PricingFactors) GetCustomFactors() map[string]float64 {
	if x != nil {
		return x.CustomFactors
	}
	return nil
}

// Vehicle type with pricing
type VehicleType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Rates         *PricingRates          `protobuf:"bytes,4,opt,name=rates,proto3" json:"rates,omitempty"`
	Capacity      int32                  `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Available     bool                   `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleType) Reset() {
	*x = VehicleType{}
	mi := &file_pricing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleType) ProtoMessage() {}

func (x *VehicleType) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleType.ProtoReflect.Descriptor instead.
func (*VehicleType) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{6}
}

func (x *VehicleType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VehicleType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VehicleType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VehicleType) GetRates() *PricingRates {
	if x != nil {
		return x.Rates
	}
	return nil
}

func (x *VehicleType) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *VehicleType) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

// Pricing rates for a vehicle type
type PricingRates struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BaseFare        float64                `protobuf:"fixed64,1,opt,name=base_fare,json=baseFare,proto3" json:"base_fare,omitempty"`
	PerKmRate       float64                `protobuf:"fixed64,2,opt,name=per_km_rate,json=perKmRate,proto3" json:"per_km_rate,omitempty"`
	PerMinuteRate   float64                `protobuf:"fixed64,3,opt,name=per_minute_rate,json=perMinuteRate,proto3" json:"per_minute_rate,omitempty"`
	MinimumFare     float64                `protobuf:"fixed64,4,opt,name=minimum_fare,json=minimumFare,proto3" json:"minimum_fare,omitempty"`
	MaximumFare     float64                `protobuf:"fixed64,5,opt,name=maximum_fare,json=maximumFare,proto3" json:"maximum_fare,omitempty"`
	BookingFee      float64                `protobuf:"fixed64,6,opt,name=booking_fee,json=bookingFee,proto3" json:"booking_fee,omitempty"`
	CancellationFee float64                `protobuf:"fixed64,7,opt,name=cancellation_fee,json=cancellationFee,proto3" json:"cancellation_fee,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PricingRates) Reset() {
	*x = PricingRates{}
	mi := &file_pricing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingRates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingRates) ProtoMessage() {}

func (x *PricingRates) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingRates.ProtoReflect.Descriptor instead.
func (*PricingRates) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{7}
}

func (x *PricingRates) GetBaseFare() float64 {
	if x != nil {
		return x.BaseFare
	}
	return 0
}

func (x *PricingRates) GetPerKmRate() float64 {
	if x != nil {
		return x.PerKmRate
	}
	return 0
}

func (x *PricingRates) GetPerMinuteRate() float64 {
	if x != nil {
		return x.PerMinuteRate
	}
	return 0
}

func (x *PricingRates) GetMinimumFare() float64 {
	if x != nil {
		return x.MinimumFare
	}
	return 0
}

func (x *PricingRates) GetMaximumFare() float64 {
	if x != nil {
		return x.MaximumFare
	}
	return 0
}

func (x *PricingRates) GetBookingFee() float64 {
	if x != nil {
		return x.BookingFee
	}
	return 0
}

func (x *PricingRates) GetCancellationFee() float64 {
	if x != nil {
		return x.CancellationFee
	}
	return 0
}

// Request/Response messages
type GetPriceEstimateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PickupLocation *Location              `protobuf:"bytes,1,opt,name=pickup_location,json=pickupLocation,proto3" json:"pickup_location,omitempty"`
	Destination    *Location              `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	VehicleType    string                 `protobuf:"bytes,3,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	DepartureTime  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	RiderId        string                 `protobuf:"bytes,5,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Options        map[string]string      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPriceEstimateRequest) Reset() {
	*x = GetPriceEstimateRequest{}
	mi := &file_pricing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceEstimateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceEstimateRequest) ProtoMessage() {}

func (x *GetPriceEstimateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceEstimateRequest.ProtoReflect.Descriptor instead.
func (*GetPriceEstimateRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{8}
}

func (x *GetPriceEstimateRequest) GetPickupLocation() *Location {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *GetPriceEstimateRequest) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *GetPriceEstimateRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *GetPriceEstimateRequest) GetDepartureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureTime
	}
	return nil
}

func (x *GetPriceEstimateRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *GetPriceEstimateRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetPriceEstimateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estimate      *PriceEstimate         `protobuf:"bytes,1,opt,name=estimate,proto3" json:"estimate,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceEstimateResponse) Reset() {
	*x = GetPriceEstimateResponse{}
	mi := &file_pricing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceEstimateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceEstimateResponse) ProtoMessage() {}

func (x *GetPriceEstimateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceEstimateResponse.ProtoReflect.Descriptor instead.
func (*GetPriceEstimateResponse) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{9}
}

func (x *GetPriceEstimateResponse) GetEstimate() *PriceEstimate {
	if x != nil {
		return x.Estimate
	}
	return nil
}

func (x *GetPriceEstimateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPriceEstimateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPriceEstimateResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type GetMultipleEstimatesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PickupLocation *Location              `protobuf:"bytes,1,opt,name=pickup_location,json=pickupLocation,proto3" json:"pickup_location,omitempty"`
	Destination    *Location              `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	VehicleTypes   []string               `protobuf:"bytes,3,rep,name=vehicle_types,json=vehicleTypes,proto3" json:"vehicle_types,omitempty"`
	DepartureTime  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	RiderId        string                 `protobuf:"bytes,5,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMultipleEstimatesRequest) Reset() {
	*x = GetMultipleEstimatesRequest{}
	mi := &file_pricing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleEstimatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleEstimatesRequest) ProtoMessage() {}

func (x *GetMultipleEstimatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleEstimatesRequest.ProtoReflect.Descriptor instead.
func (*GetMultipleEstimatesRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{10}
}

func (x *GetMultipleEstimatesRequest) GetPickupLocation() *Location {
	if x != nil {
		return x.PickupLocation
	}
	return nil
}

func (x *GetMultipleEstimatesRequest) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *GetMultipleEstimatesRequest) GetVehicleTypes() []string {
	if x != nil {
		return x.VehicleTypes
	}
	return nil
}

func (x *GetMultipleEstimatesRequest) GetDepartureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureTime
	}
	return nil
}

func (x *GetMultipleEstimatesRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

type GetMultipleEstimatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estimates     []*PriceEstimate       `protobuf:"bytes,1,rep,name=estimates,proto3" json:"estimates,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipleEstimatesResponse) Reset() {
	*x = GetMultipleEstimatesResponse{}
	mi := &file_pricing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleEstimatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleEstimatesResponse) ProtoMessage() {}

func (x *GetMultipleEstimatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleEstimatesResponse.ProtoReflect.Descriptor instead.
func (*GetMultipleEstimatesResponse) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{11}
}

func (x *GetMultipleEstimatesResponse) GetEstimates() []*PriceEstimate {
	if x != nil {
		return x.Estimates
	}
	return nil
}

func (x *GetMultipleEstimatesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMultipleEstimatesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CalculateFinalFareRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TripId                string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	ActualPickup          *Location              `protobuf:"bytes,2,opt,name=actual_pickup,json=actualPickup,proto3" json:"actual_pickup,omitempty"`
	ActualDestination     *Location              `protobuf:"bytes,3,opt,name=actual_destination,json=actualDestination,proto3" json:"actual_destination,omitempty"`
	ActualDistanceKm      float64                `protobuf:"fixed64,4,opt,name=actual_distance_km,json=actualDistanceKm,proto3" json:"actual_distance_km,omitempty"`
	ActualDurationMinutes int32                  `protobuf:"varint,5,opt,name=actual_duration_minutes,json=actualDurationMinutes,proto3" json:"actual_duration_minutes,omitempty"`
	VehicleType           string                 `protobuf:"bytes,6,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	TripStartTime         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=trip_start_time,json=tripStartTime,proto3" json:"trip_start_time,omitempty"`
	TripEndTime           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=trip_end_time,json=tripEndTime,proto3" json:"trip_end_time,omitempty"`
	Adjustments           map[string]string      `protobuf:"bytes,9,rep,name=adjustments,proto3" json:"adjustments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CalculateFinalFareRequest) Reset() {
	*x = CalculateFinalFareRequest{}
	mi := &file_pricing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateFinalFareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateFinalFareRequest) ProtoMessage() {}

func (x *CalculateFinalFareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateFinalFareRequest.ProtoReflect.Descriptor instead.
func (*CalculateFinalFareRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{12}
}

func (x *CalculateFinalFareRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *CalculateFinalFareRequest) GetActualPickup() *Location {
	if x != nil {
		return x.ActualPickup
	}
	return nil
}

func (x *CalculateFinalFareRequest) GetActualDestination() *Location {
	if x != nil {
		return x.ActualDestination
	}
	return nil
}

func (x *CalculateFinalFareRequest) GetActualDistanceKm() float64 {
	if x != nil {
		return x.ActualDistanceKm
	}
	return 0
}

func (x *CalculateFinalFareRequest) GetActualDurationMinutes() int32 {
	if x != nil {
		return x.ActualDurationMinutes
	}
	return 0
}

func (x *CalculateFinalFareRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *CalculateFinalFareRequest) GetTripStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TripStartTime
	}
	return nil
}

func (x *CalculateFinalFareRequest) GetTripEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TripEndTime
	}
	return nil
}

func (x *CalculateFinalFareRequest) GetAdjustments() map[string]string {
	if x != nil {
		return x.Adjustments
	}
	return nil
}

type CalculateFinalFareResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FinalFare        *PriceEstimate         `protobuf:"bytes,1,opt,name=final_fare,json=finalFare,proto3" json:"final_fare,omitempty"`
	OriginalEstimate *PriceEstimate         `protobuf:"bytes,2,opt,name=original_estimate,json=originalEstimate,proto3" json:"original_estimate,omitempty"`
	Adjustments      []*FareAdjustment      `protobuf:"bytes,3,rep,name=adjustments,proto3" json:"adjustments,omitempty"`
	Success          bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CalculateFinalFareResponse) Reset() {
	*x = CalculateFinalFareResponse{}
	mi := &file_pricing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateFinalFareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateFinalFareResponse) ProtoMessage() {}

func (x *CalculateFinalFareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateFinalFareResponse.ProtoReflect.Descriptor instead.
func (*CalculateFinalFareResponse) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{13}
}

func (x *CalculateFinalFareResponse) GetFinalFare() *PriceEstimate {
	if x != nil {
		return x.FinalFare
	}
	return nil
}

func (x *CalculateFinalFareResponse) GetOriginalEstimate() *PriceEstimate {
	if x != nil {
		return x.OriginalEstimate
	}
	return nil
}

func (x *CalculateFinalFareResponse) GetAdjustments() []*FareAdjustment {
	if x != nil {
		return x.Adjustments
	}
	return nil
}

func (x *CalculateFinalFareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CalculateFinalFareResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FareAdjustment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "route_change", "wait_time", "tolls", "cleanup_fee"
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FareAdjustment) Reset() {
	*x = FareAdjustment{}
	mi := &file_pricing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FareAdjustment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FareAdjustment) ProtoMessage() {}

func (x *FareAdjustment) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FareAdjustment.ProtoReflect.Descriptor instead.
func (*FareAdjustment) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{14}
}

func (x *FareAdjustment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FareAdjustment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FareAdjustment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FareAdjustment) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetSurgePricingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	VehicleType   string                 `protobuf:"bytes,2,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSurgePricingRequest) Reset() {
	*x = GetSurgePricingRequest{}
	mi := &file_pricing_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSurgePricingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSurgePricingRequest) ProtoMessage() {}

func (x *GetSurgePricingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSurgePricingRequest.ProtoReflect.Descriptor instead.
func (*GetSurgePricingRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{15}
}

func (x *GetSurgePricingRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *GetSurgePricingRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

type GetSurgePricingResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SurgeInfo         *SurgeInfo             `protobuf:"bytes,1,opt,name=surge_info,json=surgeInfo,proto3" json:"surge_info,omitempty"`
	CurrentMultiplier float64                `protobuf:"fixed64,2,opt,name=current_multiplier,json=currentMultiplier,proto3" json:"current_multiplier,omitempty"`
	IsActive          bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSurgePricingResponse) Reset() {
	*x = GetSurgePricingResponse{}
	mi := &file_pricing_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSurgePricingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSurgePricingResponse) ProtoMessage() {}

func (x *GetSurgePricingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSurgePricingResponse.ProtoReflect.Descriptor instead.
func (*GetSurgePricingResponse) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{16}
}

func (x *GetSurgePricingResponse) GetSurgeInfo() *SurgeInfo {
	if x != nil {
		return x.SurgeInfo
	}
	return nil
}

func (x *GetSurgePricingResponse) GetCurrentMultiplier() float64 {
	if x != nil {
		return x.CurrentMultiplier
	}
	return 0
}

func (x *GetSurgePricingResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetVehicleTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleTypesRequest) Reset() {
	*x = GetVehicleTypesRequest{}
	mi := &file_pricing_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleTypesRequest) ProtoMessage() {}

func (x *GetVehicleTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleTypesRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleTypesRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{17}
}

func (x *GetVehicleTypesRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type GetVehicleTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleTypes  []*VehicleType         `protobuf:"bytes,1,rep,name=vehicle_types,json=vehicleTypes,proto3" json:"vehicle_types,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleTypesResponse) Reset() {
	*x = GetVehicleTypesResponse{}
	mi := &file_pricing_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleTypesResponse) ProtoMessage() {}

func (x *GetVehicleTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleTypesResponse.ProtoReflect.Descriptor instead.
func (*GetVehicleTypesResponse) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{18}
}

func (x *GetVehicleTypesResponse) GetVehicleTypes() []*VehicleType {
	if x != nil {
		return x.VehicleTypes
	}
	return nil
}

func (x *GetVehicleTypesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateSurgePricingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ZoneId          string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Multiplier      float64                `protobuf:"fixed64,2,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,4,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateSurgePricingRequest) Reset() {
	*x = UpdateSurgePricingRequest{}
	mi := &file_pricing_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSurgePricingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSurgePricingRequest) ProtoMessage() {}

func (x *UpdateSurgePricingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSurgePricingRequest.ProtoReflect.Descriptor instead.
func (*UpdateSurgePricingRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateSurgePricingRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *UpdateSurgePricingRequest) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *UpdateSurgePricingRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateSurgePricingRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type UpdateSurgePricingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedSurge  *SurgeInfo             `protobuf:"bytes,3,opt,name=updated_surge,json=updatedSurge,proto3" json:"updated_surge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSurgePricingResponse) Reset() {
	*x = UpdateSurgePricingResponse{}
	mi := &file_pricing_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSurgePricingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSurgePricingResponse) ProtoMessage() {}

func (x *UpdateSurgePricingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSurgePricingResponse.ProtoReflect.Descriptor instead.
func (*UpdateSurgePricingResponse) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateSurgePricingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateSurgePricingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateSurgePricingResponse) GetUpdatedSurge() *SurgeInfo {
	if x != nil {
		return x.UpdatedSurge
	}
	return nil
}

type GetPricingStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromTime      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`
	ToTime        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPricingStatsRequest) Reset() {
	*x = GetPricingStatsRequest{}
	mi := &file_pricing_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPricingStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPricingStatsRequest) ProtoMessage() {}

func (x *GetPricingStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPricingStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPricingStatsRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{21}
}

func (x *GetPricingStatsRequest) GetFromTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTime
	}
	return nil
}

func (x *GetPricingStatsRequest) GetToTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTime
	}
	return nil
}

func (x *GetPricingStatsRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type PricingStats struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AverageFare            float64                `protobuf:"fixed64,1,opt,name=average_fare,json=averageFare,proto3" json:"average_fare,omitempty"`
	TotalRevenue           float64                `protobuf:"fixed64,2,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	TotalTrips             int32                  `protobuf:"varint,3,opt,name=total_trips,json=totalTrips,proto3" json:"total_trips,omitempty"`
	AverageSurgeMultiplier float64                `protobuf:"fixed64,4,opt,name=average_surge_multiplier,json=averageSurgeMultiplier,proto3" json:"average_surge_multiplier,omitempty"`
	SurgePeriods           int32                  `protobuf:"varint,5,opt,name=surge_periods,json=surgePeriods,proto3" json:"surge_periods,omitempty"`
	VehicleTypeAverages    map[string]float64     `protobuf:"bytes,6,rep,name=vehicle_type_averages,json=vehicleTypeAverages,proto3" json:"vehicle_type_averages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	DiscountUsage          map[string]int32       `protobuf:"bytes,7,rep,name=discount_usage,json=discountUsage,proto3" json:"discount_usage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PricingStats) Reset() {
	*x = PricingStats{}
	mi := &file_pricing_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingStats) ProtoMessage() {}

func (x *PricingStats) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingStats.ProtoReflect.Descriptor instead.
func (*PricingStats) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{22}
}

func (x *PricingStats) GetAverageFare() float64 {
	if x != nil {
		return x.AverageFare
	}
	return 0
}

func (x *PricingStats) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *PricingStats) GetTotalTrips() int32 {
	if x != nil {
		return x.TotalTrips
	}
	return 0
}

func (x *PricingStats) GetAverageSurgeMultiplier() float64 {
	if x != nil {
		return x.AverageSurgeMultiplier
	}
	return 0
}

func (x *PricingStats) GetSurgePeriods() int32 {
	if x != nil {
		return x.SurgePeriods
	}
	return 0
}

func (x *PricingStats) GetVehicleTypeAverages() map[string]float64 {
	if x != nil {
		return x.VehicleTypeAverages
	}
	return nil
}

func (x *PricingStats) GetDiscountUsage() map[string]int32 {
	if x != nil {
		return x.DiscountUsage
	}
	return nil
}

type GetPricingStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *PricingStats          `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPricingStatsResponse) Reset() {
	*x = GetPricingStatsResponse{}
	mi := &file_pricing_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPricingStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPricingStatsResponse) ProtoMessage() {}

func (x *GetPricingStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPricingStatsResponse.ProtoReflect.Descriptor instead.
func (*GetPricingStatsResponse) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{23}
}

func (x *GetPricingStatsResponse) GetStats() *PricingStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetPricingStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Real-time pricing updates
type PricingUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	VehicleType   string                 `protobuf:"bytes,2,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	OldMultiplier float64                `protobuf:"fixed64,3,opt,name=old_multiplier,json=oldMultiplier,proto3" json:"old_multiplier,omitempty"`
	NewMultiplier float64                `protobuf:"fixed64,4,opt,name=new_multiplier,json=newMultiplier,proto3" json:"new_multiplier,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricingUpdateEvent) Reset() {
	*x = PricingUpdateEvent{}
	mi := &file_pricing_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingUpdateEvent) ProtoMessage() {}

func (x *PricingUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingUpdateEvent.ProtoReflect.Descriptor instead.
func (*PricingUpdateEvent) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{24}
}

func (x *PricingUpdateEvent) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *PricingUpdateEvent) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *PricingUpdateEvent) GetOldMultiplier() float64 {
	if x != nil {
		return x.OldMultiplier
	}
	return 0
}

func (x *PricingUpdateEvent) GetNewMultiplier() float64 {
	if x != nil {
		return x.NewMultiplier
	}
	return 0
}

func (x *PricingUpdateEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PricingUpdateEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SubscribeToPricingUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneIds       []string               `protobuf:"bytes,1,rep,name=zone_ids,json=zoneIds,proto3" json:"zone_ids,omitempty"`
	VehicleTypes  []string               `protobuf:"bytes,2,rep,name=vehicle_types,json=vehicleTypes,proto3" json:"vehicle_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToPricingUpdatesRequest) Reset() {
	*x = SubscribeToPricingUpdatesRequest{}
	mi := &file_pricing_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToPricingUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToPricingUpdatesRequest) ProtoMessage() {}

func (x *SubscribeToPricingUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToPricingUpdatesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToPricingUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{25}
}

func (x *SubscribeToPricingUpdatesRequest) GetZoneIds() []string {
	if x != nil {
		return x.ZoneIds
	}
	return nil
}

func (x *SubscribeToPricingUpdatesRequest) GetVehicleTypes() []string {
	if x != nil {
		return x.VehicleTypes
	}
	return nil
}

var File_pricing_proto protoreflect.FileDescriptor

const file_pricing_proto_rawDesc = "" +
	"\n" +
	"\rpricing.proto\x12\apricing\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\xaa\x03\n" +
	"\rPriceEstimate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tbase_fare\x18\x02 \x01(\x01R\bbaseFare\x12#\n" +
	"\rdistance_fare\x18\x03 \x01(\x01R\fdistanceFare\x12\x1b\n" +
	"\ttime_fare\x18\x04 \x01(\x01R\btimeFare\x12)\n" +
	"\x10surge_multiplier\x18\x05 \x01(\x01R\x0fsurgeMultiplier\x12!\n" +
	"\fsurge_amount\x18\x06 \x01(\x01R\vsurgeAmount\x12'\n" +
	"\x0fdiscount_amount\x18\a \x01(\x01R\x0ediscountAmount\x12!\n" +
	"\ftotal_amount\x18\b \x01(\x01R\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x127\n" +
	"\tbreakdown\x18\n" +
	" \x01(\v2\x19.pricing.PricingBreakdownR\tbreakdown\x12;\n" +
	"\vvalid_until\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil\"\x9c\x03\n" +
	"\x10PricingBreakdown\x12\x1b\n" +
	"\tbase_rate\x18\x01 \x01(\x01R\bbaseRate\x12\x1e\n" +
	"\vper_km_rate\x18\x02 \x01(\x01R\tperKmRate\x12&\n" +
	"\x0fper_minute_rate\x18\x03 \x01(\x01R\rperMinuteRate\x12\x1f\n" +
	"\vdistance_km\x18\x04 \x01(\x01R\n" +
	"distanceKm\x12)\n" +
	"\x10duration_minutes\x18\x05 \x01(\x05R\x0fdurationMinutes\x12\x1f\n" +
	"\vbooking_fee\x18\x06 \x01(\x01R\n" +
	"bookingFee\x12\x1f\n" +
	"\vservice_fee\x18\a \x01(\x01R\n" +
	"serviceFee\x12\x14\n" +
	"\x05taxes\x18\b \x01(\x01R\x05taxes\x12\x14\n" +
	"\x05tolls\x18\t \x01(\x01R\x05tolls\x126\n" +
	"\tdiscounts\x18\n" +
	" \x03(\v2\x18.pricing.AppliedDiscountR\tdiscounts\x121\n" +
	"\n" +
	"surge_info\x18\v \x01(\v2\x12.pricing.SurgeInfoR\tsurgeInfo\"\xa4\x01\n" +
	"\x0fAppliedDiscount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12!\n" +
	"\famount_saved\x18\x05 \x01(\x01R\vamountSaved\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\xe9\x01\n" +
	"\tSurgeInfo\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x02 \x01(\x01R\n" +
	"multiplier\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x123\n" +
	"\aends_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x12\x17\n" +
	"\azone_id\x18\x06 \x01(\tR\x06zoneId\"\x8e\x03\n" +
	"\x0ePricingFactors\x12+\n" +
	"\x11demand_multiplier\x18\x01 \x01(\x01R\x10demandMultiplier\x12+\n" +
	"\x11supply_multiplier\x18\x02 \x01(\x01R\x10supplyMultiplier\x12-\n" +
	"\x12weather_multiplier\x18\x03 \x01(\x01R\x11weatherMultiplier\x12)\n" +
	"\x10event_multiplier\x18\x04 \x01(\x01R\x0feventMultiplier\x123\n" +
	"\x16time_of_day_multiplier\x18\x05 \x01(\x01R\x13timeOfDayMultiplier\x12Q\n" +
	"\x0ecustom_factors\x18\x06 \x03(\v2*.pricing.PricingFactors.CustomFactorsEntryR\rcustomFactors\x1a@\n" +
	"\x12CustomFactorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xba\x01\n" +
	"\vVehicleType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12+\n" +
	"\x05rates\x18\x04 \x01(\v2\x15.pricing.PricingRatesR\x05rates\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x05R\bcapacity\x12\x1c\n" +
	"\tavailable\x18\x06 \x01(\bR\tavailable\"\x85\x02\n" +
	"\fPricingRates\x12\x1b\n" +
	"\tbase_fare\x18\x01 \x01(\x01R\bbaseFare\x12\x1e\n" +
	"\vper_km_rate\x18\x02 \x01(\x01R\tperKmRate\x12&\n" +
	"\x0fper_minute_rate\x18\x03 \x01(\x01R\rperMinuteRate\x12!\n" +
	"\fminimum_fare\x18\x04 \x01(\x01R\vminimumFare\x12!\n" +
	"\fmaximum_fare\x18\x05 \x01(\x01R\vmaximumFare\x12\x1f\n" +
	"\vbooking_fee\x18\x06 \x01(\x01R\n" +
	"bookingFee\x12)\n" +
	"\x10cancellation_fee\x18\a \x01(\x01R\x0fcancellationFee\"\x90\x03\n" +
	"\x17GetPriceEstimateRequest\x12:\n" +
	"\x0fpickup_location\x18\x01 \x01(\v2\x11.pricing.LocationR\x0epickupLocation\x123\n" +
	"\vdestination\x18\x02 \x01(\v2\x11.pricing.LocationR\vdestination\x12!\n" +
	"\fvehicle_type\x18\x03 \x01(\tR\vvehicleType\x12A\n" +
	"\x0edeparture_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rdepartureTime\x12\x19\n" +
	"\brider_id\x18\x05 \x01(\tR\ariderId\x12G\n" +
	"\aoptions\x18\x06 \x03(\v2-.pricing.GetPriceEstimateRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x01\n" +
	"\x18GetPriceEstimateResponse\x122\n" +
	"\bestimate\x18\x01 \x01(\v2\x16.pricing.PriceEstimateR\bestimate\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"\x91\x02\n" +
	"\x1bGetMultipleEstimatesRequest\x12:\n" +
	"\x0fpickup_location\x18\x01 \x01(\v2\x11.pricing.LocationR\x0epickupLocation\x123\n" +
	"\vdestination\x18\x02 \x01(\v2\x11.pricing.LocationR\vdestination\x12#\n" +
	"\rvehicle_types\x18\x03 \x03(\tR\fvehicleTypes\x12A\n" +
	"\x0edeparture_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rdepartureTime\x12\x19\n" +
	"\brider_id\x18\x05 \x01(\tR\ariderId\"\x88\x01\n" +
	"\x1cGetMultipleEstimatesResponse\x124\n" +
	"\testimates\x18\x01 \x03(\v2\x16.pricing.PriceEstimateR\testimates\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xd2\x04\n" +
	"\x19CalculateFinalFareRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x126\n" +
	"\ractual_pickup\x18\x02 \x01(\v2\x11.pricing.LocationR\factualPickup\x12@\n" +
	"\x12actual_destination\x18\x03 \x01(\v2\x11.pricing.LocationR\x11actualDestination\x12,\n" +
	"\x12actual_distance_km\x18\x04 \x01(\x01R\x10actualDistanceKm\x126\n" +
	"\x17actual_duration_minutes\x18\x05 \x01(\x05R\x15actualDurationMinutes\x12!\n" +
	"\fvehicle_type\x18\x06 \x01(\tR\vvehicleType\x12B\n" +
	"\x0ftrip_start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rtripStartTime\x12>\n" +
	"\rtrip_end_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vtripEndTime\x12U\n" +
	"\vadjustments\x18\t \x03(\v23.pricing.CalculateFinalFareRequest.AdjustmentsEntryR\vadjustments\x1a>\n" +
	"\x10AdjustmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x02\n" +
	"\x1aCalculateFinalFareResponse\x125\n" +
	"\n" +
	"final_fare\x18\x01 \x01(\v2\x16.pricing.PriceEstimateR\tfinalFare\x12C\n" +
	"\x11original_estimate\x18\x02 \x01(\v2\x16.pricing.PriceEstimateR\x10originalEstimate\x129\n" +
	"\vadjustments\x18\x03 \x03(\v2\x17.pricing.FareAdjustmentR\vadjustments\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"v\n" +
	"\x0eFareAdjustment\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"j\n" +
	"\x16GetSurgePricingRequest\x12-\n" +
	"\blocation\x18\x01 \x01(\v2\x11.pricing.LocationR\blocation\x12!\n" +
	"\fvehicle_type\x18\x02 \x01(\tR\vvehicleType\"\x98\x01\n" +
	"\x17GetSurgePricingResponse\x121\n" +
	"\n" +
	"surge_info\x18\x01 \x01(\v2\x12.pricing.SurgeInfoR\tsurgeInfo\x12-\n" +
	"\x12current_multiplier\x18\x02 \x01(\x01R\x11currentMultiplier\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\"G\n" +
	"\x16GetVehicleTypesRequest\x12-\n" +
	"\blocation\x18\x01 \x01(\v2\x11.pricing.LocationR\blocation\"j\n" +
	"\x17GetVehicleTypesResponse\x129\n" +
	"\rvehicle_types\x18\x01 \x03(\v2\x14.pricing.VehicleTypeR\fvehicleTypes\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x97\x01\n" +
	"\x19UpdateSurgePricingRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x02 \x01(\x01R\n" +
	"multiplier\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12)\n" +
	"\x10duration_minutes\x18\x04 \x01(\x05R\x0fdurationMinutes\"\x89\x01\n" +
	"\x1aUpdateSurgePricingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\rupdated_surge\x18\x03 \x01(\v2\x12.pricing.SurgeInfoR\fupdatedSurge\"\x9e\x01\n" +
	"\x16GetPricingStatsRequest\x127\n" +
	"\tfrom_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bfromTime\x123\n" +
	"\ato_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06toTime\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"\x95\x04\n" +
	"\fPricingStats\x12!\n" +
	"\faverage_fare\x18\x01 \x01(\x01R\vaverageFare\x12#\n" +
	"\rtotal_revenue\x18\x02 \x01(\x01R\ftotalRevenue\x12\x1f\n" +
	"\vtotal_trips\x18\x03 \x01(\x05R\n" +
	"totalTrips\x128\n" +
	"\x18average_surge_multiplier\x18\x04 \x01(\x01R\x16averageSurgeMultiplier\x12#\n" +
	"\rsurge_periods\x18\x05 \x01(\x05R\fsurgePeriods\x12b\n" +
	"\x15vehicle_type_averages\x18\x06 \x03(\v2..pricing.PricingStats.VehicleTypeAveragesEntryR\x13vehicleTypeAverages\x12O\n" +
	"\x0ediscount_usage\x18\a \x03(\v2(.pricing.PricingStats.DiscountUsageEntryR\rdiscountUsage\x1aF\n" +
	"\x18VehicleTypeAveragesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a@\n" +
	"\x12DiscountUsageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"`\n" +
	"\x17GetPricingStatsResponse\x12+\n" +
	"\x05stats\x18\x01 \x01(\v2\x15.pricing.PricingStatsR\x05stats\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xf0\x01\n" +
	"\x12PricingUpdateEvent\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12!\n" +
	"\fvehicle_type\x18\x02 \x01(\tR\vvehicleType\x12%\n" +
	"\x0eold_multiplier\x18\x03 \x01(\x01R\roldMultiplier\x12%\n" +
	"\x0enew_multiplier\x18\x04 \x01(\x01R\rnewMultiplier\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"b\n" +
	" SubscribeToPricingUpdatesRequest\x12\x19\n" +
	"\bzone_ids\x18\x01 \x03(\tR\azoneIds\x12#\n" +
	"\rvehicle_types\x18\x02 \x03(\tR\fvehicleTypes2\xf5\x05\n" +
	"\x0ePricingService\x12W\n" +
	"\x10GetPriceEstimate\x12 .pricing.GetPriceEstimateRequest\x1a!.pricing.GetPriceEstimateResponse\x12c\n" +
	"\x14GetMultipleEstimates\x12$.pricing.GetMultipleEstimatesRequest\x1a%.pricing.GetMultipleEstimatesResponse\x12]\n" +
	"\x12CalculateFinalFare\x12\".pricing.CalculateFinalFareRequest\x1a#.pricing.CalculateFinalFareResponse\x12T\n" +
	"\x0fGetSurgePricing\x12\x1f.pricing.GetSurgePricingRequest\x1a .pricing.GetSurgePricingResponse\x12T\n" +
	"\x0fGetVehicleTypes\x12\x1f.pricing.GetVehicleTypesRequest\x1a .pricing.GetVehicleTypesResponse\x12]\n" +
	"\x12UpdateSurgePricing\x12\".pricing.UpdateSurgePricingRequest\x1a#.pricing.UpdateSurgePricingResponse\x12T\n" +
	"\x0fGetPricingStats\x12\x1f.pricing.GetPricingStatsRequest\x1a .pricing.GetPricingStatsResponse\x12e\n" +
	"\x19SubscribeToPricingUpdates\x12).pricing.SubscribeToPricingUpdatesRequest\x1a\x1b.pricing.PricingUpdateEvent0\x01B4Z2github.com/rideshare-platform/shared/proto/pricingb\x06proto3"

var (
	file_pricing_proto_rawDescOnce sync.Once
	file_pricing_proto_rawDescData []byte
)

func file_pricing_proto_rawDescGZIP() []byte {
	file_pricing_proto_rawDescOnce.Do(func() {
		file_pricing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pricing_proto_rawDesc), len(file_pricing_proto_rawDesc)))
	})
	return file_pricing_proto_rawDescData
}

var file_pricing_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_pricing_proto_goTypes = []any{
	(*Location)(nil),                         // 0: pricing.Location
	(*PriceEstimate)(nil),                    // 1: pricing.PriceEstimate
	(*PricingBreakdown)(nil),                 // 2: pricing.PricingBreakdown
	(*AppliedDiscount)(nil),                  // 3: pricing.AppliedDiscount
	(*SurgeInfo)(nil),                        // 4: pricing.SurgeInfo
	(*PricingFactors)(nil),                   // 5: pricing.PricingFactors
	(*VehicleType)(nil),                      // 6: pricing.VehicleType
	(*PricingRates)(nil),                     // 7: pricing.PricingRates
	(*GetPriceEstimateRequest)(nil),          // 8: pricing.GetPriceEstimateRequest
	(*GetPriceEstimateResponse)(nil),         // 9: pricing.GetPriceEstimateResponse
	(*GetMultipleEstimatesRequest)(nil),      // 10: pricing.GetMultipleEstimatesRequest
	(*GetMultipleEstimatesResponse)(nil),     // 11: pricing.GetMultipleEstimatesResponse
	(*CalculateFinalFareRequest)(nil),        // 12: pricing.CalculateFinalFareRequest
	(*CalculateFinalFareResponse)(nil),       // 13: pricing.CalculateFinalFareResponse
	(*FareAdjustment)(nil),                   // 14: pricing.FareAdjustment
	(*GetSurgePricingRequest)(nil),           // 15: pricing.GetSurgePricingRequest
	(*GetSurgePricingResponse)(nil),          // 16: pricing.GetSurgePricingResponse
	(*GetVehicleTypesRequest)(nil),           // 17: pricing.GetVehicleTypesRequest
	(*GetVehicleTypesResponse)(nil),          // 18: pricing.GetVehicleTypesResponse
	(*UpdateSurgePricingRequest)(nil),        // 19: pricing.UpdateSurgePricingRequest
	(*UpdateSurgePricingResponse)(nil),       // 20: pricing.UpdateSurgePricingResponse
	(*GetPricingStatsRequest)(nil),           // 21: pricing.GetPricingStatsRequest
	(*PricingStats)(nil),                     // 22: pricing.PricingStats
	(*GetPricingStatsResponse)(nil),          // 23: pricing.GetPricingStatsResponse
	(*PricingUpdateEvent)(nil),               // 24: pricing.PricingUpdateEvent
	(*SubscribeToPricingUpdatesRequest)(nil), // 25: pricing.SubscribeToPricingUpdatesRequest
	nil,                                      // 26: pricing.PricingFactors.CustomFactorsEntry
	nil,                                      // 27: pricing.GetPriceEstimateRequest.OptionsEntry
	nil,                                      // 28: pricing.CalculateFinalFareRequest.AdjustmentsEntry
	nil,                                      // 29: pricing.PricingStats.VehicleTypeAveragesEntry
	nil,                                      // 30: pricing.PricingStats.DiscountUsageEntry
	(*timestamppb.Timestamp)(nil),            // 31: google.protobuf.Timestamp
}
var file_pricing_proto_depIdxs = []int32{
	2,  // 0: pricing.PriceEstimate.breakdown:type_name -> pricing.PricingBreakdown
	31, // 1: pricing.PriceEstimate.valid_until:type_name -> google.protobuf.Timestamp
	3,  // 2: pricing.PricingBreakdown.discounts:type_name -> pricing.AppliedDiscount
	4,  // 3: pricing.PricingBreakdown.surge_info:type_name -> pricing.SurgeInfo
	31, // 4: pricing.SurgeInfo.started_at:type_name -> google.protobuf.Timestamp
	31, // 5: pricing.SurgeInfo.ends_at:type_name -> google.protobuf.Timestamp
	26, // 6: pricing.PricingFactors.custom_factors:type_name -> pricing.PricingFactors.CustomFactorsEntry
	7,  // 7: pricing.VehicleType.rates:type_name -> pricing.PricingRates
	0,  // 8: pricing.GetPriceEstimateRequest.pickup_location:type_name -> pricing.Location
	0,  // 9: pricing.GetPriceEstimateRequest.destination:type_name -> pricing.Location
	31, // 10: pricing.GetPriceEstimateRequest.departure_time:type_name -> google.protobuf.Timestamp
	27, // 11: pricing.GetPriceEstimateRequest.options:type_name -> pricing.GetPriceEstimateRequest.OptionsEntry
	1,  // 12: pricing.GetPriceEstimateResponse.estimate:type_name -> pricing.PriceEstimate
	0,  // 13: pricing.GetMultipleEstimatesRequest.pickup_location:type_name -> pricing.Location
	0,  // 14: pricing.GetMultipleEstimatesRequest.destination:type_name -> pricing.Location
	31, // 15: pricing.GetMultipleEstimatesRequest.departure_time:type_name -> google.protobuf.Timestamp
	1,  // 16: pricing.GetMultipleEstimatesResponse.estimates:type_name -> pricing.PriceEstimate
	0,  // 17: pricing.CalculateFinalFareRequest.actual_pickup:type_name -> pricing.Location
	0,  // 18: pricing.CalculateFinalFareRequest.actual_destination:type_name -> pricing.Location
	31, // 19: pricing.CalculateFinalFareRequest.trip_start_time:type_name -> google.protobuf.Timestamp
	31, // 20: pricing.CalculateFinalFareRequest.trip_end_time:type_name -> google.protobuf.Timestamp
	28, // 21: pricing.CalculateFinalFareRequest.adjustments:type_name -> pricing.CalculateFinalFareRequest.AdjustmentsEntry
	1,  // 22: pricing.CalculateFinalFareResponse.final_fare:type_name -> pricing.PriceEstimate
	1,  // 23: pricing.CalculateFinalFareResponse.original_estimate:type_name -> pricing.PriceEstimate
	14, // 24: pricing.CalculateFinalFareResponse.adjustments:type_name -> pricing.FareAdjustment
	0,  // 25: pricing.GetSurgePricingRequest.location:type_name -> pricing.Location
	4,  // 26: pricing.GetSurgePricingResponse.surge_info:type_name -> pricing.SurgeInfo
	0,  // 27: pricing.GetVehicleTypesRequest.location:type_name -> pricing.Location
	6,  // 28: pricing.GetVehicleTypesResponse.vehicle_types:type_name -> pricing.VehicleType
	4,  // 29: pricing.UpdateSurgePricingResponse.updated_surge:type_name -> pricing.SurgeInfo
	31, // 30: pricing.GetPricingStatsRequest.from_time:type_name -> google.protobuf.Timestamp
	31, // 31: pricing.GetPricingStatsRequest.to_time:type_name -> google.protobuf.Timestamp
	29, // 32: pricing.PricingStats.vehicle_type_averages:type_name -> pricing.PricingStats.VehicleTypeAveragesEntry
	30, // 33: pricing.PricingStats.discount_usage:type_name -> pricing.PricingStats.DiscountUsageEntry
	22, // 34: pricing.GetPricingStatsResponse.stats:type_name -> pricing.PricingStats
	31, // 35: pricing.PricingUpdateEvent.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 36: pricing.PricingService.GetPriceEstimate:input_type -> pricing.GetPriceEstimateRequest
	10, // 37: pricing.PricingService.GetMultipleEstimates:input_type -> pricing.GetMultipleEstimatesRequest
	12, // 38: pricing.PricingService.CalculateFinalFare:input_type -> pricing.CalculateFinalFareRequest
	15, // 39: pricing.PricingService.GetSurgePricing:input_type -> pricing.GetSurgePricingRequest
	17, // 40: pricing.PricingService.GetVehicleTypes:input_type -> pricing.GetVehicleTypesRequest
	19, // 41: pricing.PricingService.UpdateSurgePricing:input_type -> pricing.UpdateSurgePricingRequest
	21, // 42: pricing.PricingService.GetPricingStats:input_type -> pricing.GetPricingStatsRequest
	25, // 43: pricing.PricingService.SubscribeToPricingUpdates:input_type -> pricing.SubscribeToPricingUpdatesRequest
	9,  // 44: pricing.PricingService.GetPriceEstimate:output_type -> pricing.GetPriceEstimateResponse
	11, // 45: pricing.PricingService.GetMultipleEstimates:output_type -> pricing.GetMultipleEstimatesResponse
	13, // 46: pricing.PricingService.CalculateFinalFare:output_type -> pricing.CalculateFinalFareResponse
	16, // 47: pricing.PricingService.GetSurgePricing:output_type -> pricing.GetSurgePricingResponse
	18, // 48: pricing.PricingService.GetVehicleTypes:output_type -> pricing.GetVehicleTypesResponse
	20, // 49: pricing.PricingService.UpdateSurgePricing:output_type -> pricing.UpdateSurgePricingResponse
	23, // 50: pricing.PricingService.GetPricingStats:output_type -> pricing.GetPricingStatsResponse
	24, // 51: pricing.PricingService.SubscribeToPricingUpdates:output_type -> pricing.PricingUpdateEvent
	44, // [44:52] is the sub-list for method output_type
	36, // [36:44] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_pricing_proto_init() }
func file_pricing_proto_init() {
	if File_pricing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pricing_proto_rawDesc), len(file_pricing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pricing_proto_goTypes,
		DependencyIndexes: file_pricing_proto_depIdxs,
		MessageInfos:      file_pricing_proto_msgTypes,
	}.Build()
	File_pricing_proto = out.File
	file_pricing_proto_goTypes = nil
	file_pricing_proto_depIdxs = nil
}
