# Prometheus Configuration for Rideshare Platform
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9084']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s

  # Vehicle Service  
  - job_name: 'vehicle-service'
    static_configs:
      - targets: ['vehicle-service:9083']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s

  # Geo Service
  - job_name: 'geo-service'
    static_configs:
      - targets: ['geo-service:9081']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s

  # Trip Service
  - job_name: 'trip-service'
    static_configs:
      - targets: ['trip-service:9086']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s

  # Matching Service
  - job_name: 'matching-service'
    static_configs:
      - targets: ['matching-service:9085']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s

  # Pricing Service
  - job_name: 'pricing-service'
    static_configs:
      - targets: ['pricing-service:9087']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s

  # Payment Service
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:9088']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s

  # Infrastructure Services
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb_exporter:9216']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
  - targets: ['prometheus:9090']
