// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: shared/proto/payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payment method enumeration
type PaymentMethod int32

const (
	PaymentMethod_UNKNOWN_PAYMENT_METHOD PaymentMethod = 0
	PaymentMethod_CREDIT_CARD            PaymentMethod = 1
	PaymentMethod_DEBIT_CARD             PaymentMethod = 2
	PaymentMethod_DIGITAL_WALLET         PaymentMethod = 3
	PaymentMethod_BANK_TRANSFER          PaymentMethod = 4
	PaymentMethod_CASH                   PaymentMethod = 5
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "UNKNOWN_PAYMENT_METHOD",
		1: "CREDIT_CARD",
		2: "DEBIT_CARD",
		3: "DIGITAL_WALLET",
		4: "BANK_TRANSFER",
		5: "CASH",
	}
	PaymentMethod_value = map[string]int32{
		"UNKNOWN_PAYMENT_METHOD": 0,
		"CREDIT_CARD":            1,
		"DEBIT_CARD":             2,
		"DIGITAL_WALLET":         3,
		"BANK_TRANSFER":          4,
		"CASH":                   5,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_payment_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_shared_proto_payment_payment_proto_enumTypes[0]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{0}
}

// Payment status enumeration
type PaymentStatus int32

const (
	PaymentStatus_UNKNOWN_PAYMENT_STATUS PaymentStatus = 0
	PaymentStatus_PENDING                PaymentStatus = 1
	PaymentStatus_PROCESSING             PaymentStatus = 2
	PaymentStatus_COMPLETED              PaymentStatus = 3
	PaymentStatus_FAILED                 PaymentStatus = 4
	PaymentStatus_REFUNDED               PaymentStatus = 5
	PaymentStatus_CANCELLED              PaymentStatus = 6
	PaymentStatus_CHARGEBACK             PaymentStatus = 7
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "UNKNOWN_PAYMENT_STATUS",
		1: "PENDING",
		2: "PROCESSING",
		3: "COMPLETED",
		4: "FAILED",
		5: "REFUNDED",
		6: "CANCELLED",
		7: "CHARGEBACK",
	}
	PaymentStatus_value = map[string]int32{
		"UNKNOWN_PAYMENT_STATUS": 0,
		"PENDING":                1,
		"PROCESSING":             2,
		"COMPLETED":              3,
		"FAILED":                 4,
		"REFUNDED":               5,
		"CANCELLED":              6,
		"CHARGEBACK":             7,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_payment_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_payment_payment_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{1}
}

// Transaction type enumeration
type TransactionType int32

const (
	TransactionType_UNKNOWN_TRANSACTION_TYPE TransactionType = 0
	TransactionType_PAYMENT                  TransactionType = 1
	TransactionType_REFUND                   TransactionType = 2
	TransactionType_CHARGEBACK_TXN           TransactionType = 3
	TransactionType_AUTHORIZATION            TransactionType = 4
	TransactionType_CAPTURE                  TransactionType = 5
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "UNKNOWN_TRANSACTION_TYPE",
		1: "PAYMENT",
		2: "REFUND",
		3: "CHARGEBACK_TXN",
		4: "AUTHORIZATION",
		5: "CAPTURE",
	}
	TransactionType_value = map[string]int32{
		"UNKNOWN_TRANSACTION_TYPE": 0,
		"PAYMENT":                  1,
		"REFUND":                   2,
		"CHARGEBACK_TXN":           3,
		"AUTHORIZATION":            4,
		"CAPTURE":                  5,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_payment_payment_proto_enumTypes[2].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_shared_proto_payment_payment_proto_enumTypes[2]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{2}
}

// Fraud risk level enumeration
type FraudRiskLevel int32

const (
	FraudRiskLevel_UNKNOWN_FRAUD_RISK FraudRiskLevel = 0
	FraudRiskLevel_LOW                FraudRiskLevel = 1
	FraudRiskLevel_MEDIUM             FraudRiskLevel = 2
	FraudRiskLevel_HIGH               FraudRiskLevel = 3
)

// Enum value maps for FraudRiskLevel.
var (
	FraudRiskLevel_name = map[int32]string{
		0: "UNKNOWN_FRAUD_RISK",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
	}
	FraudRiskLevel_value = map[string]int32{
		"UNKNOWN_FRAUD_RISK": 0,
		"LOW":                1,
		"MEDIUM":             2,
		"HIGH":               3,
	}
)

func (x FraudRiskLevel) Enum() *FraudRiskLevel {
	p := new(FraudRiskLevel)
	*p = x
	return p
}

func (x FraudRiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FraudRiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_payment_payment_proto_enumTypes[3].Descriptor()
}

func (FraudRiskLevel) Type() protoreflect.EnumType {
	return &file_shared_proto_payment_payment_proto_enumTypes[3]
}

func (x FraudRiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FraudRiskLevel.Descriptor instead.
func (FraudRiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{3}
}

// Payment represents a payment transaction
type Payment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TripId            string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	UserId            string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DriverId          string                 `protobuf:"bytes,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Amount            float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod     PaymentMethod          `protobuf:"varint,7,opt,name=payment_method,json=paymentMethod,proto3,enum=payment.PaymentMethod" json:"payment_method,omitempty"`
	Status            PaymentStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	TransactionType   TransactionType        `protobuf:"varint,9,opt,name=transaction_type,json=transactionType,proto3,enum=payment.TransactionType" json:"transaction_type,omitempty"`
	ProcessorResponse string                 `protobuf:"bytes,10,opt,name=processor_response,json=processorResponse,proto3" json:"processor_response,omitempty"`
	FraudRisk         FraudRiskLevel         `protobuf:"varint,11,opt,name=fraud_risk,json=fraudRisk,proto3,enum=payment.FraudRiskLevel" json:"fraud_risk,omitempty"`
	FraudScores       map[string]float64     `protobuf:"bytes,12,rep,name=fraud_scores,json=fraudScores,proto3" json:"fraud_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Metadata          map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FailureReason     string                 `protobuf:"bytes,14,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	ProcessedAt       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *Payment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Payment) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_UNKNOWN_PAYMENT_METHOD
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_UNKNOWN_PAYMENT_STATUS
}

func (x *Payment) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_UNKNOWN_TRANSACTION_TYPE
}

func (x *Payment) GetProcessorResponse() string {
	if x != nil {
		return x.ProcessorResponse
	}
	return ""
}

func (x *Payment) GetFraudRisk() FraudRiskLevel {
	if x != nil {
		return x.FraudRisk
	}
	return FraudRiskLevel_UNKNOWN_FRAUD_RISK
}

func (x *Payment) GetFraudScores() map[string]float64 {
	if x != nil {
		return x.FraudScores
	}
	return nil
}

func (x *Payment) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Payment) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *Payment) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Payment method details
type PaymentMethodDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type           PaymentMethod          `protobuf:"varint,3,opt,name=type,proto3,enum=payment.PaymentMethod" json:"type,omitempty"`
	IsDefault      bool                   `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Fingerprint    string                 `protobuf:"bytes,5,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	ExpiryDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	LastFourDigits string                 `protobuf:"bytes,7,opt,name=last_four_digits,json=lastFourDigits,proto3" json:"last_four_digits,omitempty"`
	BankName       string                 `protobuf:"bytes,8,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	WalletProvider string                 `protobuf:"bytes,9,opt,name=wallet_provider,json=walletProvider,proto3" json:"wallet_provider,omitempty"`
	Details        map[string]string      `protobuf:"bytes,10,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentMethodDetails) Reset() {
	*x = PaymentMethodDetails{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentMethodDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentMethodDetails) ProtoMessage() {}

func (x *PaymentMethodDetails) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentMethodDetails.ProtoReflect.Descriptor instead.
func (*PaymentMethodDetails) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentMethodDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentMethodDetails) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentMethodDetails) GetType() PaymentMethod {
	if x != nil {
		return x.Type
	}
	return PaymentMethod_UNKNOWN_PAYMENT_METHOD
}

func (x *PaymentMethodDetails) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *PaymentMethodDetails) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *PaymentMethodDetails) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

func (x *PaymentMethodDetails) GetLastFourDigits() string {
	if x != nil {
		return x.LastFourDigits
	}
	return ""
}

func (x *PaymentMethodDetails) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *PaymentMethodDetails) GetWalletProvider() string {
	if x != nil {
		return x.WalletProvider
	}
	return ""
}

func (x *PaymentMethodDetails) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *PaymentMethodDetails) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentMethodDetails) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Fraud detection result
type FraudDetectionResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransactionId  string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	RiskLevel      FraudRiskLevel         `protobuf:"varint,2,opt,name=risk_level,json=riskLevel,proto3,enum=payment.FraudRiskLevel" json:"risk_level,omitempty"`
	RiskScore      float64                `protobuf:"fixed64,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Reasons        []string               `protobuf:"bytes,4,rep,name=reasons,proto3" json:"reasons,omitempty"`
	Scores         map[string]float64     `protobuf:"bytes,5,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	RequiresReview bool                   `protobuf:"varint,6,opt,name=requires_review,json=requiresReview,proto3" json:"requires_review,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FraudDetectionResult) Reset() {
	*x = FraudDetectionResult{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudDetectionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudDetectionResult) ProtoMessage() {}

func (x *FraudDetectionResult) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudDetectionResult.ProtoReflect.Descriptor instead.
func (*FraudDetectionResult) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *FraudDetectionResult) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *FraudDetectionResult) GetRiskLevel() FraudRiskLevel {
	if x != nil {
		return x.RiskLevel
	}
	return FraudRiskLevel_UNKNOWN_FRAUD_RISK
}

func (x *FraudDetectionResult) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *FraudDetectionResult) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *FraudDetectionResult) GetScores() map[string]float64 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *FraudDetectionResult) GetRequiresReview() bool {
	if x != nil {
		return x.RequiresReview
	}
	return false
}

// Request/Response messages
type ProcessPaymentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TripId          string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DriverId        string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethodId string                 `protobuf:"bytes,6,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	Description     string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessPaymentRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ProcessPaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ProcessPaymentRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProcessPaymentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *ProcessPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessPaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessPaymentResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ProcessRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,4,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRefundRequest) Reset() {
	*x = ProcessRefundRequest{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRefundRequest) ProtoMessage() {}

func (x *ProcessRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRefundRequest.ProtoReflect.Descriptor instead.
func (*ProcessRefundRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessRefundRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ProcessRefundRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ProcessRefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProcessRefundRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type ProcessRefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RefundId      string                 `protobuf:"bytes,3,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRefundResponse) Reset() {
	*x = ProcessRefundResponse{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRefundResponse) ProtoMessage() {}

func (x *ProcessRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRefundResponse.ProtoReflect.Descriptor instead.
func (*ProcessRefundResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessRefundResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessRefundResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessRefundResponse) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *ProcessRefundResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type AddPaymentMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          PaymentMethod          `protobuf:"varint,2,opt,name=type,proto3,enum=payment.PaymentMethod" json:"type,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsDefault     bool                   `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPaymentMethodRequest) Reset() {
	*x = AddPaymentMethodRequest{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentMethodRequest) ProtoMessage() {}

func (x *AddPaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*AddPaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{7}
}

func (x *AddPaymentMethodRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddPaymentMethodRequest) GetType() PaymentMethod {
	if x != nil {
		return x.Type
	}
	return PaymentMethod_UNKNOWN_PAYMENT_METHOD
}

func (x *AddPaymentMethodRequest) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *AddPaymentMethodRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type AddPaymentMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethod *PaymentMethodDetails  `protobuf:"bytes,1,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPaymentMethodResponse) Reset() {
	*x = AddPaymentMethodResponse{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentMethodResponse) ProtoMessage() {}

func (x *AddPaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*AddPaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{8}
}

func (x *AddPaymentMethodResponse) GetPaymentMethod() *PaymentMethodDetails {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

func (x *AddPaymentMethodResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddPaymentMethodResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddPaymentMethodResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{9}
}

func (x *GetPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type GetPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResponse) Reset() {
	*x = GetPaymentResponse{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResponse) ProtoMessage() {}

func (x *GetPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{10}
}

func (x *GetPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *GetPaymentResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetUserPaymentMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPaymentMethodsRequest) Reset() {
	*x = GetUserPaymentMethodsRequest{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPaymentMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPaymentMethodsRequest) ProtoMessage() {}

func (x *GetUserPaymentMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPaymentMethodsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPaymentMethodsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserPaymentMethodsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserPaymentMethodsResponse struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	PaymentMethods []*PaymentMethodDetails `protobuf:"bytes,1,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	Count          int32                   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserPaymentMethodsResponse) Reset() {
	*x = GetUserPaymentMethodsResponse{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPaymentMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPaymentMethodsResponse) ProtoMessage() {}

func (x *GetUserPaymentMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPaymentMethodsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPaymentMethodsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserPaymentMethodsResponse) GetPaymentMethods() []*PaymentMethodDetails {
	if x != nil {
		return x.PaymentMethods
	}
	return nil
}

func (x *GetUserPaymentMethodsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetUserPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPaymentsRequest) Reset() {
	*x = GetUserPaymentsRequest{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPaymentsRequest) ProtoMessage() {}

func (x *GetUserPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPaymentsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserPaymentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserPaymentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserPaymentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetUserPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPaymentsResponse) Reset() {
	*x = GetUserPaymentsResponse{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPaymentsResponse) ProtoMessage() {}

func (x *GetUserPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPaymentsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *GetUserPaymentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetUserPaymentsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetTripPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripPaymentsRequest) Reset() {
	*x = GetTripPaymentsRequest{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripPaymentsRequest) ProtoMessage() {}

func (x *GetTripPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripPaymentsRequest.ProtoReflect.Descriptor instead.
func (*GetTripPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{15}
}

func (x *GetTripPaymentsRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type GetTripPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripPaymentsResponse) Reset() {
	*x = GetTripPaymentsResponse{}
	mi := &file_shared_proto_payment_payment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripPaymentsResponse) ProtoMessage() {}

func (x *GetTripPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_payment_payment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripPaymentsResponse.ProtoReflect.Descriptor instead.
func (*GetTripPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_payment_payment_proto_rawDescGZIP(), []int{16}
}

func (x *GetTripPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *GetTripPaymentsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_shared_proto_payment_payment_proto protoreflect.FileDescriptor

const file_shared_proto_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\"shared/proto/payment/payment.proto\x12\apayment\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\a\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12=\n" +
	"\x0epayment_method\x18\a \x01(\x0e2\x16.payment.PaymentMethodR\rpaymentMethod\x12.\n" +
	"\x06status\x18\b \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12C\n" +
	"\x10transaction_type\x18\t \x01(\x0e2\x18.payment.TransactionTypeR\x0ftransactionType\x12-\n" +
	"\x12processor_response\x18\n" +
	" \x01(\tR\x11processorResponse\x126\n" +
	"\n" +
	"fraud_risk\x18\v \x01(\x0e2\x17.payment.FraudRiskLevelR\tfraudRisk\x12D\n" +
	"\ffraud_scores\x18\f \x03(\v2!.payment.Payment.FraudScoresEntryR\vfraudScores\x12:\n" +
	"\bmetadata\x18\r \x03(\v2\x1e.payment.Payment.MetadataEntryR\bmetadata\x12%\n" +
	"\x0efailure_reason\x18\x0e \x01(\tR\rfailureReason\x12=\n" +
	"\fprocessed_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a>\n" +
	"\x10FraudScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x04\n" +
	"\x14PaymentMethodDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.payment.PaymentMethodR\x04type\x12\x1d\n" +
	"\n" +
	"is_default\x18\x04 \x01(\bR\tisDefault\x12 \n" +
	"\vfingerprint\x18\x05 \x01(\tR\vfingerprint\x12;\n" +
	"\vexpiry_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\x12(\n" +
	"\x10last_four_digits\x18\a \x01(\tR\x0elastFourDigits\x12\x1b\n" +
	"\tbank_name\x18\b \x01(\tR\bbankName\x12'\n" +
	"\x0fwallet_provider\x18\t \x01(\tR\x0ewalletProvider\x12D\n" +
	"\adetails\x18\n" +
	" \x03(\v2*.payment.PaymentMethodDetails.DetailsEntryR\adetails\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x02\n" +
	"\x14FraudDetectionResult\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x126\n" +
	"\n" +
	"risk_level\x18\x02 \x01(\x0e2\x17.payment.FraudRiskLevelR\triskLevel\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x01R\triskScore\x12\x18\n" +
	"\areasons\x18\x04 \x03(\tR\areasons\x12A\n" +
	"\x06scores\x18\x05 \x03(\v2).payment.FraudDetectionResult.ScoresEntryR\x06scores\x12'\n" +
	"\x0frequires_review\x18\x06 \x01(\bR\x0erequiresReview\x1a9\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xef\x02\n" +
	"\x15ProcessPaymentRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12*\n" +
	"\x11payment_method_id\x18\x06 \x01(\tR\x0fpaymentMethodId\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12H\n" +
	"\bmetadata\x18\b \x03(\v2,.payment.ProcessPaymentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x16ProcessPaymentResponse\x12*\n" +
	"\apayment\x18\x01 \x01(\v2\x10.payment.PaymentR\apayment\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"\x88\x01\n" +
	"\x14ProcessRefundRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\frequested_by\x18\x04 \x01(\tR\vrequestedBy\"\x80\x01\n" +
	"\x15ProcessRefundResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\trefund_id\x18\x03 \x01(\tR\brefundId\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"\x82\x02\n" +
	"\x17AddPaymentMethodRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.payment.PaymentMethodR\x04type\x12G\n" +
	"\adetails\x18\x03 \x03(\v2-.payment.AddPaymentMethodRequest.DetailsEntryR\adetails\x12\x1d\n" +
	"\n" +
	"is_default\x18\x04 \x01(\bR\tisDefault\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\x18AddPaymentMethodResponse\x12D\n" +
	"\x0epayment_method\x18\x01 \x01(\v2\x1d.payment.PaymentMethodDetailsR\rpaymentMethod\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"2\n" +
	"\x11GetPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"V\n" +
	"\x12GetPaymentResponse\x12*\n" +
	"\apayment\x18\x01 \x01(\v2\x10.payment.PaymentR\apayment\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"7\n" +
	"\x1cGetUserPaymentMethodsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"}\n" +
	"\x1dGetUserPaymentMethodsResponse\x12F\n" +
	"\x0fpayment_methods\x18\x01 \x03(\v2\x1d.payment.PaymentMethodDetailsR\x0epaymentMethods\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"_\n" +
	"\x16GetUserPaymentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x83\x01\n" +
	"\x17GetUserPaymentsResponse\x12,\n" +
	"\bpayments\x18\x01 \x03(\v2\x10.payment.PaymentR\bpayments\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"1\n" +
	"\x16GetTripPaymentsRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\"]\n" +
	"\x17GetTripPaymentsResponse\x12,\n" +
	"\bpayments\x18\x01 \x03(\v2\x10.payment.PaymentR\bpayments\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count*}\n" +
	"\rPaymentMethod\x12\x1a\n" +
	"\x16UNKNOWN_PAYMENT_METHOD\x10\x00\x12\x0f\n" +
	"\vCREDIT_CARD\x10\x01\x12\x0e\n" +
	"\n" +
	"DEBIT_CARD\x10\x02\x12\x12\n" +
	"\x0eDIGITAL_WALLET\x10\x03\x12\x11\n" +
	"\rBANK_TRANSFER\x10\x04\x12\b\n" +
	"\x04CASH\x10\x05*\x90\x01\n" +
	"\rPaymentStatus\x12\x1a\n" +
	"\x16UNKNOWN_PAYMENT_STATUS\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\f\n" +
	"\bREFUNDED\x10\x05\x12\r\n" +
	"\tCANCELLED\x10\x06\x12\x0e\n" +
	"\n" +
	"CHARGEBACK\x10\a*|\n" +
	"\x0fTransactionType\x12\x1c\n" +
	"\x18UNKNOWN_TRANSACTION_TYPE\x10\x00\x12\v\n" +
	"\aPAYMENT\x10\x01\x12\n" +
	"\n" +
	"\x06REFUND\x10\x02\x12\x12\n" +
	"\x0eCHARGEBACK_TXN\x10\x03\x12\x11\n" +
	"\rAUTHORIZATION\x10\x04\x12\v\n" +
	"\aCAPTURE\x10\x05*G\n" +
	"\x0eFraudRiskLevel\x12\x16\n" +
	"\x12UNKNOWN_FRAUD_RISK\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x032\xe7\x04\n" +
	"\x0ePaymentService\x12Q\n" +
	"\x0eProcessPayment\x12\x1e.payment.ProcessPaymentRequest\x1a\x1f.payment.ProcessPaymentResponse\x12N\n" +
	"\rProcessRefund\x12\x1d.payment.ProcessRefundRequest\x1a\x1e.payment.ProcessRefundResponse\x12W\n" +
	"\x10AddPaymentMethod\x12 .payment.AddPaymentMethodRequest\x1a!.payment.AddPaymentMethodResponse\x12E\n" +
	"\n" +
	"GetPayment\x12\x1a.payment.GetPaymentRequest\x1a\x1b.payment.GetPaymentResponse\x12f\n" +
	"\x15GetUserPaymentMethods\x12%.payment.GetUserPaymentMethodsRequest\x1a&.payment.GetUserPaymentMethodsResponse\x12T\n" +
	"\x0fGetUserPayments\x12\x1f.payment.GetUserPaymentsRequest\x1a .payment.GetUserPaymentsResponse\x12T\n" +
	"\x0fGetTripPayments\x12\x1f.payment.GetTripPaymentsRequest\x1a .payment.GetTripPaymentsResponseB4Z2github.com/rideshare-platform/shared/proto/paymentb\x06proto3"

var (
	file_shared_proto_payment_payment_proto_rawDescOnce sync.Once
	file_shared_proto_payment_payment_proto_rawDescData []byte
)

func file_shared_proto_payment_payment_proto_rawDescGZIP() []byte {
	file_shared_proto_payment_payment_proto_rawDescOnce.Do(func() {
		file_shared_proto_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_payment_payment_proto_rawDesc), len(file_shared_proto_payment_payment_proto_rawDesc)))
	})
	return file_shared_proto_payment_payment_proto_rawDescData
}

var file_shared_proto_payment_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_shared_proto_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_shared_proto_payment_payment_proto_goTypes = []any{
	(PaymentMethod)(0),                    // 0: payment.PaymentMethod
	(PaymentStatus)(0),                    // 1: payment.PaymentStatus
	(TransactionType)(0),                  // 2: payment.TransactionType
	(FraudRiskLevel)(0),                   // 3: payment.FraudRiskLevel
	(*Payment)(nil),                       // 4: payment.Payment
	(*PaymentMethodDetails)(nil),          // 5: payment.PaymentMethodDetails
	(*FraudDetectionResult)(nil),          // 6: payment.FraudDetectionResult
	(*ProcessPaymentRequest)(nil),         // 7: payment.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil),        // 8: payment.ProcessPaymentResponse
	(*ProcessRefundRequest)(nil),          // 9: payment.ProcessRefundRequest
	(*ProcessRefundResponse)(nil),         // 10: payment.ProcessRefundResponse
	(*AddPaymentMethodRequest)(nil),       // 11: payment.AddPaymentMethodRequest
	(*AddPaymentMethodResponse)(nil),      // 12: payment.AddPaymentMethodResponse
	(*GetPaymentRequest)(nil),             // 13: payment.GetPaymentRequest
	(*GetPaymentResponse)(nil),            // 14: payment.GetPaymentResponse
	(*GetUserPaymentMethodsRequest)(nil),  // 15: payment.GetUserPaymentMethodsRequest
	(*GetUserPaymentMethodsResponse)(nil), // 16: payment.GetUserPaymentMethodsResponse
	(*GetUserPaymentsRequest)(nil),        // 17: payment.GetUserPaymentsRequest
	(*GetUserPaymentsResponse)(nil),       // 18: payment.GetUserPaymentsResponse
	(*GetTripPaymentsRequest)(nil),        // 19: payment.GetTripPaymentsRequest
	(*GetTripPaymentsResponse)(nil),       // 20: payment.GetTripPaymentsResponse
	nil,                                   // 21: payment.Payment.FraudScoresEntry
	nil,                                   // 22: payment.Payment.MetadataEntry
	nil,                                   // 23: payment.PaymentMethodDetails.DetailsEntry
	nil,                                   // 24: payment.FraudDetectionResult.ScoresEntry
	nil,                                   // 25: payment.ProcessPaymentRequest.MetadataEntry
	nil,                                   // 26: payment.AddPaymentMethodRequest.DetailsEntry
	(*timestamppb.Timestamp)(nil),         // 27: google.protobuf.Timestamp
}
var file_shared_proto_payment_payment_proto_depIdxs = []int32{
	0,  // 0: payment.Payment.payment_method:type_name -> payment.PaymentMethod
	1,  // 1: payment.Payment.status:type_name -> payment.PaymentStatus
	2,  // 2: payment.Payment.transaction_type:type_name -> payment.TransactionType
	3,  // 3: payment.Payment.fraud_risk:type_name -> payment.FraudRiskLevel
	21, // 4: payment.Payment.fraud_scores:type_name -> payment.Payment.FraudScoresEntry
	22, // 5: payment.Payment.metadata:type_name -> payment.Payment.MetadataEntry
	27, // 6: payment.Payment.processed_at:type_name -> google.protobuf.Timestamp
	27, // 7: payment.Payment.created_at:type_name -> google.protobuf.Timestamp
	27, // 8: payment.Payment.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 9: payment.PaymentMethodDetails.type:type_name -> payment.PaymentMethod
	27, // 10: payment.PaymentMethodDetails.expiry_date:type_name -> google.protobuf.Timestamp
	23, // 11: payment.PaymentMethodDetails.details:type_name -> payment.PaymentMethodDetails.DetailsEntry
	27, // 12: payment.PaymentMethodDetails.created_at:type_name -> google.protobuf.Timestamp
	27, // 13: payment.PaymentMethodDetails.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 14: payment.FraudDetectionResult.risk_level:type_name -> payment.FraudRiskLevel
	24, // 15: payment.FraudDetectionResult.scores:type_name -> payment.FraudDetectionResult.ScoresEntry
	25, // 16: payment.ProcessPaymentRequest.metadata:type_name -> payment.ProcessPaymentRequest.MetadataEntry
	4,  // 17: payment.ProcessPaymentResponse.payment:type_name -> payment.Payment
	0,  // 18: payment.AddPaymentMethodRequest.type:type_name -> payment.PaymentMethod
	26, // 19: payment.AddPaymentMethodRequest.details:type_name -> payment.AddPaymentMethodRequest.DetailsEntry
	5,  // 20: payment.AddPaymentMethodResponse.payment_method:type_name -> payment.PaymentMethodDetails
	4,  // 21: payment.GetPaymentResponse.payment:type_name -> payment.Payment
	5,  // 22: payment.GetUserPaymentMethodsResponse.payment_methods:type_name -> payment.PaymentMethodDetails
	4,  // 23: payment.GetUserPaymentsResponse.payments:type_name -> payment.Payment
	4,  // 24: payment.GetTripPaymentsResponse.payments:type_name -> payment.Payment
	7,  // 25: payment.PaymentService.ProcessPayment:input_type -> payment.ProcessPaymentRequest
	9,  // 26: payment.PaymentService.ProcessRefund:input_type -> payment.ProcessRefundRequest
	11, // 27: payment.PaymentService.AddPaymentMethod:input_type -> payment.AddPaymentMethodRequest
	13, // 28: payment.PaymentService.GetPayment:input_type -> payment.GetPaymentRequest
	15, // 29: payment.PaymentService.GetUserPaymentMethods:input_type -> payment.GetUserPaymentMethodsRequest
	17, // 30: payment.PaymentService.GetUserPayments:input_type -> payment.GetUserPaymentsRequest
	19, // 31: payment.PaymentService.GetTripPayments:input_type -> payment.GetTripPaymentsRequest
	8,  // 32: payment.PaymentService.ProcessPayment:output_type -> payment.ProcessPaymentResponse
	10, // 33: payment.PaymentService.ProcessRefund:output_type -> payment.ProcessRefundResponse
	12, // 34: payment.PaymentService.AddPaymentMethod:output_type -> payment.AddPaymentMethodResponse
	14, // 35: payment.PaymentService.GetPayment:output_type -> payment.GetPaymentResponse
	16, // 36: payment.PaymentService.GetUserPaymentMethods:output_type -> payment.GetUserPaymentMethodsResponse
	18, // 37: payment.PaymentService.GetUserPayments:output_type -> payment.GetUserPaymentsResponse
	20, // 38: payment.PaymentService.GetTripPayments:output_type -> payment.GetTripPaymentsResponse
	32, // [32:39] is the sub-list for method output_type
	25, // [25:32] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_shared_proto_payment_payment_proto_init() }
func file_shared_proto_payment_payment_proto_init() {
	if File_shared_proto_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_payment_payment_proto_rawDesc), len(file_shared_proto_payment_payment_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_payment_payment_proto_goTypes,
		DependencyIndexes: file_shared_proto_payment_payment_proto_depIdxs,
		EnumInfos:         file_shared_proto_payment_payment_proto_enumTypes,
		MessageInfos:      file_shared_proto_payment_payment_proto_msgTypes,
	}.Build()
	File_shared_proto_payment_payment_proto = out.File
	file_shared_proto_payment_payment_proto_goTypes = nil
	file_shared_proto_payment_payment_proto_depIdxs = nil
}
